c_compiler:
  - m2w64-toolchain
  - clang
  - vs2022
cxx_compiler:
  - m2w64-toolchain
  - clang
  - vs2022
fortran_compiler:
  - flang
  - m2w64_fortran
  - flang

python:
- 3.11.* *_cpython
target_platform:
- win-64