c_compiler:
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
  - gcc                        # [unix]
c_compiler_version:
  - 8                          # [unix]
cxx_compiler:
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
  - gxx                        # [unix]
cxx_compiler_version:
  - 8                          # [unix]
fortran_compiler:
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:
  - 8        # [unix]

mpi:
  - nompi
#  - mpich  # [unix]
#  - openmpi  # [unix]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
