c_compiler:
  - vs2022
cxx_compiler:
  - vs2022

#fortran_compiler:
#  - flang  # this is a popular choice for Fortran on Windows, but you can adjust as needed
#  - m2w64_fortran  # this is a popular choice for Fortran on Windows, but you can adjust as needed
#  - intel-fortran-rt

m2w64_fortran_compiler:        # [win]
  - m2w64-toolchain            # [win]

#fortran_compiler_version:
#  - '5'
#  - '2023.2.0'

python:
- 3.11.* *_cpython
target_platform:
- win-64