{% set name = "hdf5" %}
{% set version = "1.10.9" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name }}
  version: {{ version }}  # Adjust the version accordingly

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
#    - {{ compiler('m2w64_fortran') }}     # [win]
    - cmake
    - ninja  # optional: can use make if you prefer

test:
  commands:
    - if exist %LIBRARY_PREFIX%\lib\libhdf5_fortran.lib (exit 0) else (exit 1)  # [win]

about:
  home: https://www.hdfgroup.org/
  license: BSD-3-Clause
  license_file: COPYING
  summary: HDF5 with Fortran enabled

