{% set version = "7.7.0" %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  git_url: https://github.com/tpaviot/pythonocc-core.git


build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  binary_relocation: false [osx]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig 4.0.2

  host:
    - python
    - occt-core =={{ version }}
    - numpy >=1.17

  run:
    - python
    - occt-core =={{ version }}
    - six
    - numpy >=1.17

#test:
#  imports:
#    - OCC
#    - OCC.Core.BRepPrimAPI
#  requires:
#    - mypy
#    - svgwrite
#
about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package