{% set name = "spooles" %}
{% set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: http://www.netlib.org/linalg/spooles/spooles.2.2.tgz
  sha256: a84559a0e987a1e423055ef4fdf3035d55b65bbe4bf915efaa1a35bef7f8c5dd
  patches:
    - patches/gcc.patch  # [unix]
    - patches/win.patch  # [win]
    - patches/osx.patch

build:
  number: 1005

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - rsync  # [unix]
    - make
    #- m2-base  # [win]
    - perl

test:
  commands:
    - test -f ${PREFIX}/lib/spoolesMT.a  # [unix]

about:1
  home: http://www.netlib.org/linalg/spooles/spooles.2.2.html
  summary: 'library for solving sparse real and complex linear systems of equations'
  license: Public Domain
  license_family: Public Domain
  description: |
    SPOOLES is a library for solving sparse real and complex linear systems of equations,
    written in the C language using object oriented design.
  doc_url: http://www.netlib.org/linalg/spooles/spooles.2.2.html

extra:
  recipe-maintainers:
    - looooo
