name: conda-build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-build 3.25
#  - conda-verify # does not work together with .conda files
  - anaconda-client
  - pyyaml
  - ninja
  - doxygen
  - boa
  - mercurial
  # for windows and fortran compiler install the following
#    - m2w64-gcc-fortran
