name: mamba-build # For local testing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-build
  - conda 23.3.1
#  - conda-verify # does not work together with .conda files
  - anaconda-client
  - typer
  - quetz-client
  - python-dotenv
  - pytest
  - pandas
  - tabulate
  - pyyaml
  - ninja
  - doxygen
  - boa
  - mercurial
  - ruamel.yaml.jinja2
  - pybind11-stubgen
  - pip
  - pip:
      - -e src/cpack