name: gmsh-env
channels:
  - conda-forge
dependencies:
  - doxygen
  - python==3.9.7
  - vs2017_win-64
  - freetype==2.10.4
  - ninja
  - zlib
  - jpeg
  - libpng
  - xorg-libxext
  - xorg-libxdmcp
  - xorg-libxau
  - libxcb
  - xorg-libxfixes
  - xorg-libxrender
  - xorg-libx11
  - xorg-libice
  - xorg-libsm