name: conda-build
channels:
  - conda-forge
dependencies:
  - conda-build
  - conda-verify
  - anaconda-client
  - ninja
  - doxygen
  - boa
  - mercurial
  # for windows and fortran compiler install the following
#    - m2w64-gcc-fortran