name: gmsh-build-env
channels:
  - conda-forge
dependencies:
  - conda-build
  - conda-verify
  - anaconda-client
  - vs2019_win-64
  - python==3.9.7
  - ninja
  - zlib
  - libpng
  - fltk
  - hdf5
  - freetype
  - occt==7.5.3