name: mamba-build # For local testing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-build 3.24
#  - conda-verify # does not work together with .conda files
  - anaconda-client
  - typer
  - quetz-client
  - python-dotenv
  - pyyaml
  - ninja
  - doxygen
  - boa
  - mercurial
  - ruamel.yaml.jinja2
  - pybind11-stubgen 2.1
  - pip
  - pip:
      - -e src/cpack