{% set name = "topologic-core" %}
{% set version = "8.0.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-source.tgz
  url: https://github.com/wassimj/Topologic/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c29953364d91f8523403f9f7c244d1e6462243027882273a52731cdc9bf1238e
  patches:
    - patches/do_not_use_pybind11_subdir.patch

build:
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pybind11
  host:
    - occt
    - scipy
    - python
  run:
    - numpy


about:
  home: https://topologic.app/
  license_family: AGPL
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: Data Exchange with ISO 10303 (STEP) standards
  description: |
    Topologic is a software modelling library enabling hierarchical and topological 
    representations of architectural spaces, buildings and artefacts through non-manifold topology
  dev_url: https://github.com/wassimj/Topologic

extra:
  recipe-maintainers:
    - Krande
