schema_version: 1

context:
  name: topologic-core
  version: 8.0.0
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/wassimj/Topologic/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c29953364d91f8523403f9f7c244d1e6462243027882273a52731cdc9bf1238e
  file_name: ${{ name }}-${{ version }}-source.tgz

build:
  number: ${{ build }}

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - occt
    - scipy
    - python
  run:
    - numpy
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x.x') }}

about:
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: Data Exchange with ISO 10303 (STEP) standards
  description: |
    Topologic is a software modelling library enabling hierarchical and topological
    representations of architectural spaces, buildings and artefacts through non-manifold topology
  homepage: https://topologic.app/
  repository: https://github.com/wassimj/Topologic

extra:
  recipe-maintainers:
    - Krande