name: ci-matrix-builder
description: "A composite action to generate a JSON matrix for platforms or Python versions, and configure Conda channels."

inputs:
  python_versions:
    description: "Python versions to include in the matrix."
    required: false
    default: ""
  platforms:
    description: "Runner OS to target in the matrix."
    required: false
    default: ""
  variants:
    description: "Conda package variants in key=value pairs, separated by commas."
    required: false
    default: ""

outputs:
  final_matrix:
    value: ${{ steps.set-matrix.outputs.final_matrix }}
    description: "JSON string of the final matrix."

runs:
  using: "composite"
  steps:
    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: v0.34.0
        environments: "cpack"
        cache: true

    - name: Set matrix
      id: set-matrix
      shell: bash
      run: |
        pixi run cpack-actions matrix-builder --python-versions="${{ inputs.python_versions }}" --platforms="${{ inputs.platforms }}" --variants="${{ inputs.variants }}"
      env:
        GITHUB_OUTPUT: ${{ steps.set-matrix.outputs.final_matrix }}

    - name: Print final_matrix
      shell: bash
      run: echo "final_matrix=${{ steps.set-matrix.outputs.final_matrix }}"