context:
  name: asrun
  version: 2021.0.1-1

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  hg_url: http://hg.code.sf.net/p/prereq/frontend
  hg_tag: '{{ version }}'

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps -vv --prefix=${PREFIX}'

requirements:
  host:
    - python
  run:
    - python

test:
  commands:
    - as_run --info

about:
  home: http://www.code-aster.org
  license: GPL
  summary: interface to code_aster services

