{% set data = load_setup_py_data(from_recipe_dir=True) %}
{% set description = data.get('long_description') %}


package:
  name: minimal-test
  version: 0.0.4

source:
  - path: .

build:
  skip: True  # [py2k]

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://ifcopenshell.org/
  license: LGPL-3.0-or-later
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    {{ description }}
  doc_url: https://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - Krande