{% set name = "libmed" %}
{% set version = "4.0.0" %}
#{% set sha256 = "dc2b5d54ebf0666e3ff2e974041d2ab0da906061323537023ab165d573389dd0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://files.salome-platform.org/Salome/other/med-{{ version }}.tar.gz
  #sha256: {{ sha256 }}
    #git_url: https://salsa.debian.org/science-team/med-fichier
    #git_rev: 8a0b0d21d4bac79772797b0a800cf4d5bf77bc32    

build:
  number: 0

requirements:
  build:
      - {{ compiler('fortran') }} # [unix] 
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - swig
  host:
      - autoconf  # [linux]
      - make  # [linux]
      - ninja  # [win]
      - cmake  # [win]  
      - hdf5 >=1.10.2,<1.11
      - python
  run:
      - {{ pin_compatible('hdf5', min_pin='x.x', max_pin='x.x') }}
      - python

test:
  imports:
    - med

about:
  home: https://www.salome-platform.org/user-section/about/med
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'MED : interoperable format for data interchange between mesh based solvers.'
  description: |
    The purpose of the MED module is to provide a standard for storing and recovering computer data associated to numerical meshes and fields, and to facilitate the exchange between codes and solvers.
  doc_url: http://www.salome-platform.org/
  dev_url: http://www.salome-platform.org/

extra:
  recipe-maintainers:
    - looooo
    - ldallolio-irt
