{% set data = load_setup_py_data() %}
{% set version = "0.0.1" %}

package:
  name: minimal-test
  version: {{ version }}

source:
  - path: .

build:
  skip: True  # [py2k]

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://ifcopenshell.org/
  license: LGPL-3.0-or-later
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: README.md
  doc_url: https://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell

extra:
  recipe-maintainers:
    - looooo
    - Krande