mkdir build && cd build

cmake -G "Ninja" ^
 -D CMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
 -D CMAKE_BUILD_TYPE=Release ^
 -D CMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -D CMAKE_SYSTEM_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -D Python3_FIND_STRATEGY=LOCATION ^
 -D Python3_FIND_REGISTRY=NEVER ^
 -D OCC_INCLUDE_DIR="%LIBRARY_PREFIX%\include\opencascade" ^
 -D OCC_LIBRARY_DIR="%LIBRARY_PREFIX%\lib" ^
 -D CGAL_INCLUDE_DIR="%LIBRARY_PREFIX%\include" ^
 -D GMP_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D MPFR_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D HDF5_INCLUDE_DIR:FILEPATH="%LIBRARY_PREFIX%\include" ^
 -D HDF5_LIBRARY_DIR:FILEPATH="%LIBRARY_PREFIX%\lib" ^
 -D COLLADA_SUPPORT=OFF ^
 -D BUILD_EXAMPLES=OFF ^
 -D BUILD_GEOMSERVER=ON ^
 -D BUILD_CONVERT=OFF ^
 -D BUILD_IFCPYTHON=ON ^
 -D BUILD_IFCGEOM=ON ^
 -D IFCXML_SUPPORT=ON ^
 -D MSVC_EXTRA_WARNINGS=OFF ^
 %SRC_DIR%/cmake
if errorlevel 1 exit 1

:: Build and install
cmake --build . -- install

if errorlevel 1 exit 1
