#!/bin/bash

declare -a CMAKE_PLATFORM_FLAGS


if [ `uname` == Darwin ]; then

  cmake -G Ninja \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=$PREFIX \
    ${CMAKE_PLATFORM_FLAGS[@]} \
   -DCMAKE_PREFIX_PATH=$PREFIX \
   -DCMAKE_SYSTEM_PREFIX_PATH=$PREFIX \
   -DPython3_FIND_STRATEGY=LOCATION \
   -DPython3_FIND_FRAMEWORK=NEVER \
   -DGMP_LIBRARY_DIR=$PREFIX/lib \
   -DMPFR_LIBRARY_DIR=$PREFIX/lib \
   -DOCC_INCLUDE_DIR=$PREFIX/include/opencascade \
   -DOCC_LIBRARY_DIR=$PREFIX/lib \
   -DHDF5_SUPPORT:BOOL=ON \
   -DHDF5_INCLUDE_DIR=$PREFIX/include \
   -DHDF5_LIBRARY_DIR=$PREFIX/lib \
   -DJSON_INCLUDE_DIR=$PREFIX/include \
   -DCGAL_INCLUDE_DIR=$PREFIX/include \
   -DCOLLADA_SUPPORT:BOOL=OFF \
   -DBUILD_EXAMPLES:BOOL=OFF \
   -DIFCXML_SUPPORT:BOOL=OFF \
   -DBUILD_CONVERT:BOOL=ON \
   -DBUILD_IFCPYTHON:BOOL=ON \
   -DBUILD_IFCGEOM:BOOL=ON \
   -DBUILD_GEOMSERVER:BOOL=OFF \
   -DIFCXML_SUPPORT:BOOL=OFF \
   -DBOOST_USE_STATIC_LIBS:BOOL=OFF \
   -DCMAKE_OSX_SYSROOT=/Applications/Xcode_13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk \
   ./cmake

else
  CMAKE_PLATFORM_FLAGS+=(-DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/cross-linux.cmake")

  cmake -G Ninja \
   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=$PREFIX \
    ${CMAKE_PLATFORM_FLAGS[@]} \
   -DCMAKE_PREFIX_PATH=$PREFIX \
   -DCMAKE_SYSTEM_PREFIX_PATH=$PREFIX \
   -DPython3_FIND_STRATEGY=LOCATION \
   -DPython3_FIND_FRAMEWORK=NEVER \
   -DGMP_LIBRARY_DIR=$PREFIX/lib \
   -DMPFR_LIBRARY_DIR=$PREFIX/lib \
   -DOCC_INCLUDE_DIR=$PREFIX/include/opencascade \
   -DOCC_LIBRARY_DIR=$PREFIX/lib \
   -DHDF5_SUPPORT:BOOL=ON \
   -DHDF5_INCLUDE_DIR=$PREFIX/include \
   -DHDF5_LIBRARY_DIR=$PREFIX/lib \
   -DJSON_INCLUDE_DIR=$PREFIX/include \
   -DCGAL_INCLUDE_DIR=$PREFIX/include \
   -DCOLLADA_SUPPORT=0 \
   -DBUILD_EXAMPLES:BOOL=OFF \
   -DIFCXML_SUPPORT:BOOL=OFF \
   -DBUILD_CONVERT:BOOL=ON \
   -DBUILD_IFCPYTHON:BOOL=ON \
   -DBUILD_IFCGEOM:BOOL=ON \
   -DBUILD_GEOMSERVER:BOOL=OFF \
   -DIFCXML_SUPPORT:BOOL=OFF \
   -DBOOST_USE_STATIC_LIBS:BOOL=OFF \
   ./cmake

fi

ninja

ninja install
