{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set occt_version = "7.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/IfcOpenShell/IfcOpenShell

build:
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja ==1.10.2
    - cmake
    - swig ==4.0.2

  host:
    - python {{ python }}
    - occt =={{ occt_version }}
    - cgal-cpp ==5.3

  run:
    - python
    - occt =={{ occt_version }}
    - lark-parser
    - deepdiff
    - cgal-cpp ==5.3

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell
