{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set occt_version = "7.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/IfcOpenShell/IfcOpenShell

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - boost-cpp
    - cgal
    - hdf5
    - occt=={{ occt_version }}
    - libxml2
  run:
    - python
    - boost-cpp
    - occt=={{ occt_version }}
    - libxml2

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell
