{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}
{% set occt_version = "7.5.3" %}
{% set cgal_cpp_version = "5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/Krande/IfcOpenShell
  git_branch: v0.7.0-ada-dev

build:
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja >=1.10.2
    - cmake
    - swig >=4.0.2

  host:
    - python
    - occt =={{ occt_version }}
    - cgal-cpp =={{ cgal_cpp_version }}
    - hdf5
    - nlohmann_json

  run:
    - python
    - occt =={{ occt_version }}
    - lark-parser
    - deepdiff
    - cgal-cpp =={{ cgal_cpp_version }}
    - hdf5
    - numpy
    - requests
    - nlohmann_json
    - isodate

test:
  imports:
    - ifcopenshell

about:
  home: http://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: http://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell
