occt:
  - 7.7.2=novtk*
  - 7.7.2=all*

pin_run_as_build:
  occt: x.x.x

CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.13.sdk       # [osx]

c_compiler:
  - vs2019                     # [win]

cxx_compiler:
  - vs2019                     # [win]