{% set name = "ifcopenshell" %}
{% set version = "0.7.11.240801" %}

{% set build = 0 %}

# Prioritize the 'novtk' build variant for reduced file size
{% if "novtk" in occt %}
  {% set build = build + 200 %}
  {% set variant_name = "novtk" %}
{% elif "all" in occt %}
  {% set build = build + 100 %}
  {% set variant_name = "all" %}
{% endif %}

{% if mpi == 'nompi' %}
  {% set build = build + 1 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/IfcOpenShell/ifcopenshell.git
  git_depth: 1
  #patches:
  #  - patches/hierarchy_helper_fix.patch

build:
  binary_relocation: false [osx]
  number: {{ build }}
  string: py{{ CONDA_PY }}_{{ variant_name }}_{{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage(name, 'x.x') }} *{{ variant_name }}*

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - ninja
    - swig >=4.1.1
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - libboost-devel
    - occt 7.7.2=*{{ variant_name }}*
    - libxml2
    - cgal-cpp
    - numpy
    - hdf5
    - eigen
    - mpfr
    - nlohmann_json
    - gmp  # [unix]
    - mpir  # [win]
    - zlib
  run:
    - python
    - {{ pin_compatible('occt', max_pin='x.x.x') }} *{{ variant_name }}*
    - {{ pin_compatible('cgal-cpp', max_pin='x.x') }}

test:
  imports:
    - ifcopenshell
  commands:
    - pytest .
  files:
    - ./test_basic_ifc_ops.py
  requires:
    - pytest

about:
  home: https://ifcopenshell.org
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: 'IfcOpenShell is a library to support the IFC file format'
  description: |
    IfcOpenShell is an open source (LGPL) software library for 
    working with the Industry Foundation Classes (IFC) file format.
  doc_url: https://ifcopenshell.org/
  dev_url: https://github.com/IfcOpenShell/IfcOpenShell