name: "Prepare job"
description: "Prepare job for conda package compilation"

inputs:
  conda_channel:
    description: "Conda channel"
    required: true
  extra_build_args:
    description: "Extra build arguments"
    required: false
    default: ""
  variants:
    description: "Conda package variants in key=value pairs, separated by commas"
    required: false
    default: ""
  variants_base64_str:
    description: "Base64 encoded string of the variants"
    required: false
    default: ""
  variant_yaml_base64_str:
    description: "Base64 encoded string of the variant yaml"
    required: false
    default: ""
  env_vars:
    description: "Environment variables in key=value pairs, separated by commas"
    required: false
    default: ""
  use_devtools:
    description: "Use devtools channel"
    required: false
    default: 'false'
  quetz_url:
    description: "Quetz URL"
    required: false
    default: ""
  clean_env:
    description: "Clean environment"
    required: false
    default: 'false'


outputs:
  yaml_file_path:
    description: "Path to the yaml file"
    value: ${{ steps.set-yaml-file.outputs.yaml_file_path }}

runs:
  using: "composite"
  steps:
    - name: Set Swap Space
      if: runner.os == 'Linux'
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Configure pagefile
      if: runner.os == 'Windows'
      uses: al-cheb/configure-pagefile-action@v1.2

    - name: Set up pagefile
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize

    - name: create variant_str (if exists)
      shell: bash
      if: ${{ inputs.variants }}
      env:
        ENV_VARS_INPUT: ${{ inputs.env_vars }}
      run: |
        python3 <<EOF
        import base64
        import os

        env_file = os.environ.get("GITHUB_ENV", None)
        decoded_bytes = base64.b64decode("${{ inputs.variants_base64_str }}")
        decoded_str = decoded_bytes.decode("utf-8")

        with open(env_file, "a") as my_file:
          my_file.write(f"VARIANT_STR={decoded_str}\n")

        input_env_vars = os.environ.get("ENV_VARS_INPUT", None)
        if input_env_vars:
          input_env_vars = input_env_vars.split(",")
          for env_var in input_env_vars:
            env_var = env_var.strip()
            if env_var:
              env_var_name, env_var_value = env_var.split("=")
              env_var_value = env_var_value.replace("__root__", os.environ["GITHUB_WORKSPACE"])
              with open(env_file, "a") as my_file:
                my_file.write(f"{env_var_name}={env_var_value}\n")
        EOF

    - name: Create yaml file for conda build
      if: ${{ inputs.variant_yaml_base64_str }}
      id: set-yaml-file
      shell: bash
      run: |
        python3 <<EOF
        import base64
        import pathlib
        import os

        decoded_bytes = base64.b64decode("${{ inputs.variant_yaml_base64_str }}")
        decoded_str = decoded_bytes.decode("utf-8")
        
        yaml_path = pathlib.Path(os.environ["GITHUB_WORKSPACE"]) / "ci_ga_conda_build.yaml"
        
        with open(yaml_path, "w") as my_file:
          my_file.write(decoded_str)
        
        with open(os.environ["GITHUB_OUTPUT"], "a") as my_file:
          my_file.write(f"yaml_file_path={yaml_path.as_posix()}\n")

        EOF

    - name: Evaluate Extra Build Args
      env:
        EXTRA_ARGS: ${{ inputs.extra_build_args }}
        QUETZ_URL: ${{ inputs.quetz_url }}
        CONDA_CHANNEL: ${{ inputs.conda_channel }}
        WORKSPACE: ${{ github.workspace}}
        USE_DEVTOOLS: ${{ inputs.use_devtools }}
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/set_extra_build_vars.py

    - name: Download and extract MacOSX SDK
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.15.sdk.tar.xz | tar -xvJf - -C /Users/runner/work/

    - name: Update SHELL_NAME if running windows
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      run: |
        echo "SHELL_NAME=bash cmd.exe" >> $GITHUB_ENV

    - name: set ENV vars
      shell: bash
      run: |
        pwd
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "PKG_DIR=win-64" >> $GITHUB_ENV
          echo "WORK_DIR=D:/a/" >> $GITHUB_ENV
          echo "ARTIFACTS_DIR=D:/a/artifacts" >> $GITHUB_ENV
          echo "CROOT_DIR=D:/a/build" >> $GITHUB_ENV
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "PKG_DIR=osx-64" >> $GITHUB_ENV
          echo "WORK_DIR=/Users/runner/work" >> $GITHUB_ENV
          echo "ARTIFACTS_DIR=/Users/runner/work/artifacts" >> $GITHUB_ENV
          echo "CROOT_DIR=/Users/runner/work/build" >> $GITHUB_ENV
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          echo "PKG_DIR=linux-64" >> $GITHUB_ENV
          echo "WORK_DIR=/home/runner/work" >> $GITHUB_ENV
          echo "ARTIFACTS_DIR=/home/runner/work/artifacts" >> $GITHUB_ENV
          echo "CROOT_DIR=/home/runner/work/build" >> $GITHUB_ENV
        fi

    # For some reason on linux, the runner swig is chosen over the conda swig
    - name: try to remove swig on linux
      shell: bash
      if: ${{ runner.os == 'Linux' }} # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
      continue-on-error: true
      run: |
        sudo apt remove swig make
        sudo rm -r /usr/bin/swig4.0
        sudo rm -rf /usr/share/miniconda

    - name: make dirs
      shell: bash
      run: |
        mkdir -p ${{ env.ARTIFACTS_DIR }}
        mkdir -p ${{ env.CROOT_DIR }}

    - name: Give necessary permissions on linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo chmod -R +x ${{ env.WORK_DIR }}

    - name: Clean up PATH on windows
      if: ${{ runner.os == 'Windows' && inputs.clean_env == 'true' }}
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/env_cleaner.py