{% set name = "metis" %}
{% set version = "5.1.0" %}
{% set aster_variant = "aster4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - hg_url: http://hg.code.sf.net/p/prereq/metis
    hg_tag: '{{ version }}_{{ aster_variant }}'

build:
  detect_binary_files_with_prefix: true
  string: '{{ aster_variant }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}'
  number: 1

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - make

about:
  home: http://glaros.dtc.umn.edu/gkhome/views/metis/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning finite element meshes, and producing fill reducing orderings for sparse matrices. The algorithms implemented in METIS are based on the multilevel recursive-bisection, multilevel k-way, and multi-constraint partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/views/metis/index.html


extra:
  recipe-maintainers:
    - Krande