{% set name = "metis" %}
{% set version = "5.1.0.4" %}
{% set aster_variant = "aster4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: 'METIS_scivision_{{ version }}.tar.gz'
    url: https://github.com/scivision/METIS/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 26b55bc1cfb2267a64f45240d280deeff19743f211eb9a00c68f2b0cb7be4aa3

build:
  detect_binary_files_with_prefix: true
  script: bld.bat # [win]
  string: '{{ aster_variant }}_{{ build_type }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}'
  number: 3
  run_exports:
    - {{ pin_subpackage(name, 'x.x') }} *{{ build_type}}*

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - ninja
    - cmake

test:
  commands:
    # Check for existence of files and directories
    - test -f $PREFIX/lib/libmetis.so # [linux]
    - test -f $PREFIX/include/metis.h # [linux]

about:
  home: https://github.com/KarypisLab/METIS
  license: Apache-2.0
  license_family: Apache
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning finite element meshes, and producing fill reducing orderings for sparse matrices. The algorithms implemented in METIS are based on the multilevel recursive-bisection, multilevel k-way, and multi-constraint partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/views/metis/index.html


extra:
  recipe-maintainers:
    - Krande