{% set name = "metis" %}
{% set version = "5.1.0" %}
{% set aster_variant = "aster4" %}
{% set prereq_file = "codeaster-prerequisites-20240327-oss" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: "{{ prereq_file }}.tar.gz"
    url: https://github.com/Krande/condapackaging/releases/download/{{ prereq_file }}/{{ prereq_file }}.tar.gz
    sha256: d3a94ba2c01c1f5866ece9f940581c3801a632c2245169d2a90112ebcdb6c67e
    folder: deps/

build:
  detect_binary_files_with_prefix: true
  string: '{{ aster_variant }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}'
  number: 3
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}" # [not win]
    - make

test:
  commands:
    # Check for existence of files and directories
    - test -f $PREFIX/lib/libmetis.so
    - test -f $PREFIX/include/metis.h

about:
  home: http://glaros.dtc.umn.edu/gkhome/views/metis/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    METIS is a set of serial programs for partitioning graphs, partitioning finite element meshes, and producing fill reducing orderings for sparse matrices. The algorithms implemented in METIS are based on the multilevel recursive-bisection, multilevel k-way, and multi-constraint partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/views/metis/index.html


extra:
  recipe-maintainers:
    - Krande