# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "fltk" %}
{% set version = "1.3.10" %}
{% set md5 = "ec8075e5ba09f85b531e332b535fbf29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://fltk.org/pub/{{ name }}/{{ version }}/{{ name }}-{{ version }}-source.tar.bz2
  md5: {{ md5 }}
  patches:
    # This patch will change on the next release....
    - skip_problematic_test.patch
    - Window.diff  # [osx]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("fltk", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make   # [unix]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('expat') }}             # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - freetype                       # [linux]
    - gnuconfig                      # [unix]

  host:
    - zlib
    - libjpeg-turbo
    - libpng
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - libxcb
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - libglu    # [linux]
    - freetype  # [linux]

  run:
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libxau
    - libxcb
    - xorg-libxfixes
    - xorg-libxrender
    - xorg-libx11
    - xorg-libice
    - xorg-libsm
    - libglu    # [linux]
    - freetype  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libfltk.a  # [unix]
    - test -f $PREFIX/lib/libfltk${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libfltk_gl.a  # [unix]
    - if not exist %LIBRARY_LIB%\\fltk.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\fltk_forms.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\fltk_images.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\fltk_gl.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libfltk.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libfltk.dll exit 1  # [win]

about:
  home: https://www.fltk.org/
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: The Fast Light Tool Kit ("FLTK", pronounced "fulltick") is a cross-platform C++ GUI toolkit

  description: |
    FLTK (pronounced "fulltick") is a cross-platform C++ GUI toolkit for
    UNIX/Linux (X11), Microsoft Windows, and MacOS X. FLTK provides
    modern GUI functionality without the bloat and supports 3D graphics via
    OpenGL and its built-in GLUT emulation.

    FLTK is designed to be small and modular enough to be statically
    linked, but works fine as a shared library. FLTK also includes an
    excellent UI builder called FLUID that can be used to create
    applications in minutes.
  doc_url: https://www.fltk.org/documentation.php
  dev_url: https://github.com/fltk/fltk.git

extra:
  recipe-maintainers:
    - guyer
    - matthiasdiener