c_compiler:
  - vs2022   # [win]
  - gcc      # [unix]
cxx_compiler:
  - vs2022   # [win]
  - gxx      # [unix]
fortran_compiler:
  - gfortran # [unix]

mpi:
  - openmpi=4.1.6

pin_run_as_build:
  openmpi: x.x

numpy:
  - 1.25
  - 1.26

python:
  - 3.11
  - 3.12

zip_keys:
  - numpy
  - python