{% set build = 1005 %}
{% set version = "4.0.3" %}
{% set aster_variant = "aster3" %}
{% set sha256 = "ecbc4c943b24d948857458ddc44ec256f6cbb24ce8ca3964bcc2444fdf2040a2" %}

package:
  name: parmetis
  version: {{ version }}

source:
  url: https://github.com/Krande/parmetis-aster-copy/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: {{ build }}
  string: aster1_py{{ CONDA_PY }}_mpi_{{mpi}}_np{{CONDA_NPY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

  host:
    - {{ mpi }}

  run:
    - {{ mpi }}

test:
  commands:
    - test -f "${PREFIX}/include/parmetis.h"
    - test -f "${PREFIX}/lib/libparmetis.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libparmetis.so"  # [linux]

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: Non-free for commercial use
  license_file: LICENSE.txt
  summary: 'ParMETIS - Parallel Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    ParMETIS is an MPI-based parallel library that implements a
    variety of algorithms for partitioning unstructured graphs,
    meshes, and for computing fill-reducing orderings of sparse
    matrices. ParMETIS extends the functionality provided by METIS and
    includes routines that are especially suited for parallel AMR
    computations and large scale numerical simulations. The algorithms
    implemented in ParMETIS are based on the parallel multilevel k-way
    graph-partitioning, adaptive repartitioning, and parallel
    multi-constrained partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/manual.pdf

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - isuruf
    - minrk
    - davidbrochart