#!/bin/bash

# Use 'run_ctest --help' for detailed description of the options.

export RUNASTER_ROOT=${CONDA_PREFIX}
export ASTER_ELEMENTSDIR="${CONDA_PREFIX}/lib/aster"
python3 -m run_aster.run_ctest_main "${@}"
exit ${?}
