#!/bin/bash

mkdir -p build
cd build


cmake .. \
    -DCMAKE_INSTALL_PREFIX=install \
    -DCONFIGURATION_ROOT_DIR="./deps/salome" \
    -DMEDCOUPLING_MICROMED:BOOL=ON \
    -DMEDCOUPLING_BUILD_DOC=OFF \
    -DMEDCOUPLING_ENABLE_PARTITIONER=OFF \
    -DMEDCOUPLING_BUILD_TESTS=OFF \
    -DMEDCOUPLING_ENABLE_RENUMBER=OFF \
    -DMEDCOUPLING_WITH_FILE_EXAMPLES=OFF \
    -DMEDCOUPLING_USE_64BIT_IDS=OFF
