c_compiler:
  - vs2022   # [win]
  - gcc      # [unix]
cxx_compiler:
  - vs2022   # [win]
  - gxx      # [unix]
fortran_compiler:
  - gfortran # [unix]

blas_impl:
  - openblas

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  libmed:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x

numpy:
  - 1.25
  - 1.26

python:
  - 3.11
  - 3.12

zip_keys:
  - numpy
  - python

hdf5:
  - 1.14.2=nompi*

mpi:
  - openmpi               # [not win]
  - nompi
