c_compiler_version:
  - 12
cxx_compiler_version:
  - 12
fortran_compiler_version:
  - 12

blas_impl:
  - openblas

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  libmed:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x

numpy:
  - 1.26

python:
  - 3.12

hdf5:
  - 1.14.2=nompi*

mpi:
  - openmpi               # [not win]
  - nompi
