c_compiler_version:
  - 8
cxx_compiler_version:
  - 8
fortran_compiler_version:
  - 8

blas_impl:
  - openblas

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  libmed:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x

boost:
  - 1.78
numpy:
  - '1.25'

hdf5:
  - 1.10.6=mpi*openmpi*   # [unix]
  - 1.10.6=nompi*         # [unix]
  - 1.10.10=nompi*        # [win]

mpi:
  - openmpi               # [not win]
  - nompi

zip_keys:
  - mpi
  - hdf5
