context:
  name: medcoupling
  version: 9.10.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:

  - fn: 'medcoupling_{{ version }}.tar.gz'
    url: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git;a=snapshot;h=fe2e38d301902c626f644907e00e499552bb2fa5;sf=tgz # 9.10
#    url: https://git.salome-platform.org/gitweb/?p=tools/medcoupling.git;a=snapshot;h=1b5fb5650409b0ad3a61da3215496f2adf2dae02;sf=tgz # 9.11
  - fn: 'config_{{ version }}.tar.gz'
    url: https://git.salome-platform.org/gitweb/?p=tools/configuration.git;a=snapshot;h=25f724f7a6c0000330a40c3851dcd8bc2493e1fa;sf=tgz # 9.10.0
    folder: deps/config

build:
  detect_binary_files_with_prefix: true
  number: 0

requirements:
  build:
    - cmake
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - swig

  host:
    - libmed
    - python
    - boost-cpp
    - libxml2

  run:
    - "{{ pin_compatible('libmed', max_pin='x.x') }}"

about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande