# This file was generated by CMake because it detected try_run() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _med_int_run_result
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _med_int_run_result to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# _med_int_run_result__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set _med_int_run_result__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The _med_int_compile_results variable holds the build result for this try_run().
# 
# Source file   : /home/krande/mambaforge/envs/conda-build/conda-bld/medcoupling-0_1693224367540/work/build/CMakeFiles/CMakeTmp/check_med_int_size.cxx
# Executable    : /home/krande/mambaforge/envs/conda-build/conda-bld/medcoupling-0_1693224367540/work/build/CMakeFiles/cmTC_14898-_med_int_run_result
# Run arguments : 
#    Called from: [2]	/home/krande/mambaforge/envs/conda-build/conda-bld/medcoupling-0_1693224367540/work/deps/config/cmake/FindSalomeMEDFile.cmake
#                 [1]	/home/krande/mambaforge/envs/conda-build/conda-bld/medcoupling-0_1693224367540/work/CMakeLists.txt

set(_med_int_run_result "0" CACHE STRING "Result from try_run" FORCE)
set(_med_int_run_result__TRYRUN_OUTPUT "" CACHE STRING "Output from try_run" FORCE)
