python:
  - 3.11
python_impl:
  - cpython
channel_targets:
  - conda-forge python_debug
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
build_type:
  - debug
tk:
  - '8.6'