bzip2:
- '1'
c_compiler:
- vs2022
c_stdlib:
- vs
c_stdlib_version:
- '2022'
channel_sources:
- conda-forge

cxx_compiler:
- vs2022
expat:
- '2'
libffi:
- '3.4'
openssl:
- '3'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x

sqlite:
- '3'
target_platform:
- win-64
tk:
- '8.6'
xz:
- '5'

zlib:
- '1.2'

python:
  - 3.11
python_impl:
  - cpython
numpy:
  - 1.23
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
build_type:
#  - release
  - debug

channel_targets:
  - conda-forge main
  - conda-forge python_debug   # [not win]

zip_keys:
  - build_type
  - channel_targets
