occt:
  - 7.7.2=novtk*
  - 7.7.2=all*

pin_run_as_build:
  occt: x.x.x

CONDA_BUILD_SYSROOT:
  - "/Users/runner/work/MacOSX10.15.sdk"  # [osx]

c_compiler:
 - vs2022                     # [win]
 - gcc                        # [unix]
cxx_compiler:
 - vs2022                     # [win]
 - gxx                        # [unix]


cxx_compiler_version:         # [unix]
- '12'                        # [unix]
c_compiler_version:           # [unix]
- '12'                        # [unix]

zlib:
- '1.2'
cairo:
- '1'
cdt_name:
- cos6