c_compiler:
  - vs2022                     # [win]
  - gcc                        # [linux]
  - clang                      # [osx]
cxx_compiler:
  - vs2022                     # [win]
  - gxx                        # [linux]
  - clangxx                    # [osx]

c_compiler_version:           # [not win]
  - 8                          # [linux]
  - 15                         # [osx]
cxx_compiler_version:          # [not win]
  - 8                          # [linux]
  - 15                         # [osx]

fortran_compiler:
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - intel-fortran-rt           # [win]

fortran_compiler_version:
  - '8'                          # [linux]
  - '12'                         # [osx]
  - '2023.2'                     # [win]

mpi:
  - nompi
  - mpich  # [unix]
  - openmpi  # [unix]

MACOSX_SDK_VERSION: # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
