c_compiler:
  - m2w64-toolchain            # [win and arm64]
  - gcc                        # [linux]
  - clang                      # [osx]
c_compiler_version:
  - 8                          # [unix]
cxx_compiler:
  - m2w64-toolchain            # [win and arm64]
  - gxx                        # [linux]
  - clangxx                    # [osx
cxx_compiler_version:
  - 8                          # [unix]
fortran_compiler:
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - m2w64-toolchain            # [win64]

fortran_compiler_version:
  - '8'                          # [linux]
  - '12'                         # [osx]

mpi:
  - nompi
  - mpich  # [unix]
  - openmpi  # [unix]

MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]

