c_compiler:                     # [not win]
  - gcc                         # [linux]
  - clang                       # [osx]
cxx_compiler:                   # [not win]
  - gxx                         # [linux]
  - clangxx                     # [osx]

c_compiler_version:             # [not win]
  - 8                           # [linux]
  - 15                          # [osx]
cxx_compiler_version:           # [not win]
  - 8                           # [linux]
  - 15                          # [osx]

fortran_compiler: # [not win]
  - gfortran                    # [linux64 or (osx and x86_64)]
  - gfortran                    # [aarch64 or ppc64le or armv7l or s390x]

fortran_compiler_version:       # [not win]
  - '8'                         # [linux]
  - '12'                        # [osx]

mpi:
  - nompi
  - mpich                       # [unix]
  - openmpi                     # [unix]

compiler_win:
  - intel
  - mingw
  - flang

MACOSX_SDK_VERSION:           # [osx and x86_64]
  - "10.15"                   # [osx and x86_64]
