c_compiler:
  - vs2022                     # [win]
cxx_compiler:
  - vs2022                     # [win]
fortran_compiler:
  - intel-fortran-rt           # [win]
fortran_compiler_version:
  - '2023.2'                   # [win]