c_compiler:
  - vs2022                     # [win]
cxx_compiler:
  - vs2022                     # [win]
fortran_compiler:
  - flang                      # [win]
fortran_compiler_version:
  - '17'                       # [win]