{% set version = "1.10.9" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
  # prioritize nompi via build number
  {% set build = build + 100 %}
{% endif %}

{% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
{% else %}
  {% set mpi_prefix = "nompi" %}
{% endif %}
# add build string so packages can depend on
# mpi or nompi variants
# dependencies:
# `hdf5 * mpi_mpich_*` for mpich
# `hdf5 * mpi_*` for any mpi
# `hdf5 * nompi_*` for no mpi

# mpi builds require the right mpi
# non-mpi builds *do not* appear to require non-mpi builds
# at least not always

{% if mpi != 'nompi' %}
  {% set build_pin = mpi_prefix + '_*' %}
{% else %}
  {% set build_pin = '' %}
{% endif %}

{% set PKG_DEBUG = environ.get('PKG_DEBUG', 'False') %}
{% set USE_INTEL = environ.get('USE_INTEL', 'False') %}
{% set USE_FLANG = environ.get('USE_FLANG', 'False') %}

package:
  name: hdf5
  version: {{ version }}

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz

build:
  number: {{ build }}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('hdf5', max_pin='x.x.x') }} {{ build_pin }}
  script_env:
    - PKG_DEBUG={{ PKG_DEBUG }}
    - USE_INTEL={{ USE_INTEL }}
    - USE_FLANG={{ USE_FLANG }}
  script: # [win]
    - {{ RECIPE_DIR }}/{{ 'bld_intel.bat' if USE_INTEL == 'True' else 'bld.bat' }}  # [win]


requirements:
  build:
    - gnuconfig                   # [unix]
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('cxx') }}       # [not win]
    - {{ compiler('fortran') }}   # [not win]
    {% if USE_INTEL == 'True' %}  # [win]
    - vs2022_win-64=*19.36*       # [win]
    - {{ compiler('c') }}         # [win]
    - {{ compiler('cxx') }}       # [win]
    - intel-fortran-rt            # [win]
    {% else %}                    # [win]
    - mingw64 13.1                # [win]
    {% endif %}                   # [win]
    - cmake                       # [win]
    - automake                    # [not win]
    - autoconf                    # [not win]
    - libtool                     # [not win]
    - make                        # [not win]
    - ninja                       # [win]
    # Keep both versions of openssl in sync
    - openssl
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - zlib
    - libaec
    - libcurl
    - openssl
  run:
    - {{ mpi }}  # [mpi != 'nompi']

test:
  requires:
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('cxx') }}       # [not win]
    - {{ compiler('fortran') }}   # [not win]
    - m2w64-toolchain             # [win]
    - pkg-config                  # [not win]
    - cmake                       # [not win]
    - make                        # [not win]
    # Need zlib to compile test programs
    - zlib
  files:
    - compound_fortran2003.f90
    - h5_cmprss.c
    - h5_cmprss.f90
    - h5tutr_cmprss.cpp
  commands:
    - command -v h5c++
    - command -v h5cc
    - command -v h5fc
    - command -v h5redeploy
    - command -v h5perf_serial
    - command -v gif2h5
    - command -v h52gif
    - command -v h5copy
    - command -v h5debug
    - command -v h5diff
    - command -v h5dump
    - command -v h5import
    - command -v h5jam
    - command -v h5ls
    - command -v h5mkgrp
    - command -v h5repack
    - command -v h5repart
    - command -v h5stat
    - command -v h5unjam
    - test -f $PREFIX/lib/libhdf5${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_cpp${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl${SHLIB_EXT}
    - test -f $PREFIX/lib/libhdf5_hl_cpp${SHLIB_EXT}

about:
  home: https://www.hdfgroup.org/solutions/hdf5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing data
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5

extra:
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - gillins
    - groutr
    - ocefpaf
    - astrofrog
    - marqh
    - marcelotrevisani
    - scopatz
    - davidbrochart
    - SylvainCorlay
    - varlackc
