schema_version: 1

context:
  name: hdf5
  version: 1.14.6
  build_base: 11
  mpi_num: ${{ 100 if mpi == 'nompi' else 0 }}
  build: ${{ (200 if build_type == 'release' else 0) + mpi_num|int + build_base|int }}
  mpi_prefix: ${{ mpi or 'nompi' }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5_${{ version }}.tar.gz
  sha256: 09ee1c671a87401a5201c06106650f62badeea5a3b3941e9b1e2e1e08317357f

build:
  number: ${{ build }}
  string: ${{ mpi_prefix }}_${{ build_type }}_h${{ hash }}_${{ build }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: not win
      then:
        - gnuconfig
        - automake
        - autoconf
        - libtool
        - make
    - if: win
      then:
        - ninja
        - cmake
    - openssl
  host:
    - zlib
    - libaec
    - libcurl
    - openssl
  run:
    - zlib
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - files:
      recipe:
        - test/
        - run_test.sh
        - run_test.bat
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
        - if: not win
          then:
            - pkg-config
            - cmake
            - make
        - zlib
    script:
      - if: not win
        then: ./run_test.sh
      - if: win
        then: run_test.bat

about:
  license: LicenseRef-HDF5
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing data
  homepage: https://www.hdfgroup.org/solutions/hdf5/
  repository: https://github.com/HDFGroup/hdf5
  documentation: https://portal.hdfgroup.org/display/HDF5/HDF5

extra:
  recipe-maintainers:
    - hmaarrfk
    - jakirkham
    - gillins
    - groutr
    - ocefpaf
    - astrofrog
    - marqh
    - marcelotrevisani
    - scopatz
    - davidbrochart
    - SylvainCorlay
    - varlackc

