c_compiler:
  - vs2022                # [win]
  - gcc                   # [unix]
cxx_compiler:
  - vs2022                # [win]
  - gxx                   # [unix]
fortran_compiler:
  - gfortran              # [unix]

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  boost:
    max_pin: x.x.x
  metis:
    max_pin: x.x.x
  scotch:
    max_pin: x.x.x
  libblas: x.x
  liblapack: x.x
  openmpi: x.x            # [mpi != "nompi"]

mpi:
  - openmpi
  - nompi

numpy:
  - 1.25
  - 1.26

python:
  - 3.11
  - 3.12

zip_keys:
  - numpy
  - python