{% set name = "mumps" %}
{% set version = "5.6.2" %}
# Dependencies
{% set metis_ver = "5.1.0" %}
{% set parmetis_ver = "4.0.3" %}
{% set scalapack_ver = "2.1.0" %}
{% set scotch_ver = "7.0.4" %}
{% set prereq_file = "codeaster-prerequisites-20240327-oss" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: "{{ prereq_file }}.tar.gz"
    url: https://github.com/Krande/condapackaging/releases/download/{{ prereq_file }}/{{ prereq_file }}.tar.gz
    sha256: d3a94ba2c01c1f5866ece9f940581c3801a632c2245169d2a90112ebcdb6c67e
    folder: deps/
#  - hg_url: http://hg.code.sf.net/p/prereq/mumps
#    hg_tag: '{{ version }}'


build:
  detect_binary_files_with_prefix: true
  string: aster1_py{{ CONDA_PY }}_mpi_{{mpi}}_np{{CONDA_NPY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }} # [mpi != "nompi"]
  string: aster1_py{{ CONDA_PY }}_nompi_np{{CONDA_NPY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}     # [mpi == "nompi"]
  number: 2
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}
  run_exports:
    - {{ pin_subpackage(name, 'x.x') }} {{ mpi }}*

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - waf
    - make

  host:
    - python
    - numpy
    - zlib
    - libblas
    - liblapack
    - metis {{ metis_ver }}=aster4*
    - scotch {{ scotch_ver }}
    - parmetis {{ parmetis_ver }}               # [mpi != "nompi"]
    - scalapack {{ scalapack_ver }}             # [mpi != "nompi"]
    - {{ mpi }}                                 # [mpi != "nompi"]

  run:
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}                                 # [mpi != "nompi"]


test:
  commands:
    # Check for existence of mumps libraries
    - test -f $PREFIX/lib/libcmumps.so
    - test -f $PREFIX/lib/libdmumps.so
    - test -f $PREFIX/lib/libmumps_common.so
    - test -f $PREFIX/lib/libmpiseq.so           # [mpi == "nompi"]
    - test -f $PREFIX/lib/libpord.so
    - test -f $PREFIX/lib/libsmumps.so
    - test -f $PREFIX/lib/libzmumps.so

about:
  home: https://mumps-solver.org/index.php
  license: CeCILL-C free/libre
  summary: 'MUMPS is a library which provides a powerful sparse direct parallel solver'
  description: |
    MUMPS is a library which provides a powerful sparse direct parallel solver. It is available in Code_Aster’s linear solvers both for sequential and parallel use.
  dev_url: https://github.com/scivision/mumps

extra:
  recipe-maintainers:
    - Krande
