{% set name = "mumps" %}
{% set version = "5.5.1" %}

{% set mpi = mpi or 'nompi' %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: "codeaster-prerequisites-20221225-oss.tar.gz"
    url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
    sha256: c03c9662358867ad4753d56b5f87b1687a63b31baeb7127cf179b913edb7e239
    folder: deps/
#  - hg_url: http://hg.code.sf.net/p/prereq/mumps
#    hg_tag: '{{ version }}'


build:
  detect_binary_files_with_prefix: true
  string: aster1_py{{ CONDA_PY }}{{mpi}}np{{CONDA_NPY}}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  number: 2
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - waf
    - sysroot_linux-64 2.17
    - make
    - python
    - {{ mpi }}               # [mpi != "nompi"]

  host:
    - python
    - numpy
    - libgomp
    - libblas
    - liblapack
    - metis 5.1.0=aster4*
    - scotch 7.0.1            # [mpi == "nompi"]
    - zlib
    - parmetis 4.0.3          # [mpi != "nompi"]
    - scotch 7.0.1=*openmpi*  # [mpi != "nompi"]
    - scalapack 2.1.0         # [mpi != "nompi"]
    - {{ mpi }}               # [mpi != "nompi"]

  run:
    - numpy
    - metis
    - scotch 7.0.1             # [mpi == "nompi"]
    - python
    - scalapack 2.1.0          # [mpi != "nompi"]
    - {{ mpi }}                # [mpi != "nompi"]
    - scotch 7.0.1=*openmpi*   # [mpi != "nompi"]
    - parmetis 4.0.3           # [mpi != "nompi"]


test:
  commands:
    # Check for existence of mumps libraries
    - test -f $PREFIX/lib/libcmumps.a
    - test -f $PREFIX/lib/libdmumps.a
    - test -f $PREFIX/lib/libmumps_common.a
    - test -f $PREFIX/lib/libmpiseq.a           # [mpi == "nompi"]
    - test -f $PREFIX/lib/libpord.a
    - test -f $PREFIX/lib/libsmumps.a
    - test -f $PREFIX/lib/libzmumps.a

about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C free/libre
  summary: 'MUMPS is a library which provides a powerful sparse direct parallel solver'
  description: |
    MUMPS is a library which provides a powerful sparse direct parallel solver. It is available in Code_Aster’s linear solvers both for sequential and parallel use.
  dev_url: https://github.com/scivision/mumps

extra:
  recipe-maintainers:
    - Krande
