{% set name = "mumps" %}
{% set version = "5.7.2" %}

# Dependencies
{% set metis_ver = "5.1.0" %}
{% set parmetis_ver = "4.0.3" %}
{% set scalapack_ver = "2.1.0" %}
{% set scotch_ver = "7.0.4" %}

{% set build = 2 %}

# prioritize release over debug
{% if build_type == 'release' %}
{% set build = build + 200 %}
{% endif %}

{% if mpi == 'nompi' %}
# prioritize nompi variant via build number
{% set build = build + 100 %}
{% endif %}
# add build string so packages can depend on
# mpi or nompi variants explicitly:
# `pkg * mpi_mpich_*` for mpich
# `pkg * mpi_*` for any mpi
# `pkg * nompi_*` for no mpi

{% if mpi != 'nompi' %}
{% set mpi_prefix = "mpi_" + mpi %}
{% else %}
{% set mpi_prefix = "nompi" %}
{% endif %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/Krande/mumps/archive/refs/tags/v5.7.2.2.tar.gz
    sha256: 5810cd68efadb99675a92a08a0e50eb7eae24ca35d4d6ddc9537dfc09f144f6f


build:
  detect_binary_files_with_prefix: true
  string: aster_py{{ CONDA_PY }}_{{mpi_prefix}}_{{ build_type }}_h{{ PKG_HASH }}_{{ build }}
  number: {{ build }}
  ignore_run_exports:
    - llvm-openmp  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} *{{ build_type}}*

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"  # [not win]
    - ninja
    - cmake 3.29
    - m2-patch    # [win]

  host:
    - python
    - numpy
    - zlib
    - libblas
    - liblapack
    - mkl-devel  # [win]
    - metis {{ metis_ver }}=*{{build_type}}*
    - scotch {{ scotch_ver }}=*aster*{{build_type}}*
    - parmetis {{ parmetis_ver }}               # [mpi != "nompi"]
    - scalapack {{ scalapack_ver }}             # [mpi != "nompi"]
    - {{ mpi }}                                 # [mpi != "nompi"]

  run:
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}                                 # [mpi != "nompi"]


test:
  files:
    - test_files_exists.bat
  commands:
    # Check for existence of mumps libraries
    - test -f $PREFIX/lib/libcmumps.so            # [linux]
    - test -f $PREFIX/lib/libdmumps.so            # [linux]
    - test -f $PREFIX/lib/libmumps_common.so      # [linux]
    - test -f $PREFIX/lib/libmpiseq.so            # [linux and mpi == "nompi"]
    - test -f $PREFIX/lib/libpord.so              # [linux]
    - test -f $PREFIX/lib/libsmumps.so            # [linux]
    - test -f $PREFIX/lib/libzmumps.so            # [linux]
    # same for windows not using test
    - test_files_exists.bat                       # [win]
    # Check for existence of mumps headers
    - test -f %LIBRARY_PREFIX%/include/cmumps_c.h # [win]

about:
  home: https://mumps-solver.org/index.php
  license: CeCILL-C
  summary: 'MUMPS is a library which provides a powerful sparse direct parallel solver'
  description: |
    MUMPS is a library which provides a powerful sparse direct parallel solver. It is available in Code_Aster’s linear solvers both for sequential and parallel use.
  dev_url: https://github.com/scivision/mumps

extra:
  recipe-maintainers:
    - Krande
