schema_version: 1

context:
  name: mumps
  version: 5.7.2
  build_base: 5
  build: ${{ (200 if build_type == 'release' else 0) + int_type|int + build_base|int }}
  mpi_prefix: ${{ mpi or 'nompi' }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/Krande/mumps/archive/refs/tags/v5.7.2.2.tar.gz
    sha256: 5810cd68efadb99675a92a08a0e50eb7eae24ca35d4d6ddc9537dfc09f144f6f
    patches:
      - patches/0001-Respect-openmp-option-for-IntelLLVM-and-MSVC-guard-OpenMP-flags.patch
      - patches/0002-Suppress-argument-mismatch-warnings-for-gfortran.patch

build:
  number: ${{ build }}
  string: aster_py${{ python | replace('.', '') }}_${{ mpi_prefix }}_${{ build_type }}_INT${{ int_type }}_h${{ hash }}_${{ build }}
  prefix_detection:
    ignore_binary_files: true


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - numpy
    - zlib
    - libblas
    - liblapack
    - if: win
      then:
        - mkl-devel
    - metis * *${{ build_type }}*INT${{ int_type }}*
    - scotch * *aster*${{ build_type }}*INT${{ int_type }}*
  run:
    - ${{ pin_compatible('numpy') }}
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
tests:
  - if: win
    then:
      - script:
          file: run_win_test.bat
          env:
            INT_TYPE: ${{ int_type }}
        files:
          recipe:
            - run_win_test.bat
            - tests/
        requirements:
          run:
            - ${{ compiler('fortran') }}
            - python
  - if: linux
    then:
      - script:
          - test -f $PREFIX/lib/libcmumps.so
          - test -f $PREFIX/lib/libdmumps.so
          - test -f $PREFIX/lib/libmumps_common.so
          - test -f $PREFIX/lib/libpord.so
          - test -f $PREFIX/lib/libsmumps.so
          - test -f $PREFIX/lib/libzmumps.so

about:
  license: CECILL-C
  summary: MUMPS is a library which provides a powerful sparse direct parallel solver
  description: |
    MUMPS is a library which provides a powerful sparse direct parallel solver. It is available in Code_Aster’s linear solvers both for sequential and parallel use.
  homepage: https://mumps-solver.org/index.php
  repository: https://github.com/scivision/mumps

extra:
  recipe-maintainers:
    - Krande
