schema_version: 1

context:
  name: mumps
  version: 5.7.2
  metis_ver: 5.1.0
  scotch_ver: 7.0.4
  build: ${{ ((build | int + 200) if build_type == 'release' else build|int) + int_type|int }}
  mpi_prefix: nompi

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/Krande/mumps/archive/refs/tags/v5.7.2.2.tar.gz
    sha256: 5810cd68efadb99675a92a08a0e50eb7eae24ca35d4d6ddc9537dfc09f144f6f

build:
  number: ${{ build }}
  string: aster_py${{ python | replace('.', '') }}_${{ mpi_prefix }}_${{ build_type }}_INT${{ int_type }}_h${{ hash }}_${{ build }}
  prefix_detection:
    ignore_binary_files: true


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: not win
      then:
       - ${{ compiler('fortran') }}
       - waf
       - make
    - if: win
      then: cmake
  host:
    - python
    - numpy
    - zlib
    - libblas
    - liblapack
    - if: win
      then: mkl-devel
    - metis ${{ metis_ver }}.* *${{ build_type }}*INT${{ int_type }}*
    - scotch ==${{ scotch_ver }} *aster*${{ build_type }}*INT${{ int_type }}*
  run:
    - ${{ pin_compatible('numpy') }}
  ignore_run_exports:
    by_name:
      - llvm-openmp
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - script:
      - if: linux
        then: test -f $PREFIX/lib/libcmumps.so
      - if: linux
        then: test -f $PREFIX/lib/libdmumps.so
      - if: linux
        then: test -f $PREFIX/lib/libmumps_common.so
      - if: linux
        then: test -f $PREFIX/lib/libpord.so
      - if: linux
        then: test -f $PREFIX/lib/libsmumps.so
      - if: linux
        then: test -f $PREFIX/lib/libzmumps.so
      - if: win
        then: test_files_exists.bat
      - if: win
        then: test -f %LIBRARY_PREFIX%/include/cmumps_c.h
    files:
      recipe:
        - test_files_exists.bat

about:
  license: CECILL-C
  summary: MUMPS is a library which provides a powerful sparse direct parallel solver
  description: |
    MUMPS is a library which provides a powerful sparse direct parallel solver. It is available in Code_Aster’s linear solvers both for sequential and parallel use.
  homepage: https://mumps-solver.org/index.php
  repository: https://github.com/scivision/mumps

extra:
  recipe-maintainers:
    - Krande
