c_compiler_version:
  - 8
cxx_compiler_version:
  - 8
fortran_compiler_version:
  - 8

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  boost:
    max_pin: x.x.x
  mfront:
    max_pin: x.x.x

numpy:
  - '1.25'

hdf5:
  - 1.10.6=nompi*

boost:
  - 1.78
