boost:
 - 1.78

c_compiler:
 - vs2022  # [win]
 - gcc     # [unix]
c_compiler_version:
- '9'     # [unix]
cxx_compiler:
 - vs2022  # [win]
 - gxx     # [unix]
cxx_compiler_version:
 - '9'
fortran_compiler:
 - gfortran # [unix]
fortran_compiler_version:
 - '9'      # [unix]

pin_run_as_build:
  mfront:
    max_pin: x.x.x