---
boost:
  - 1.78

c_compiler:
  - vs2022 # [win]
  - gcc    # [unix]
c_compiler_version:
  - 8    # [unix]
cxx_compiler:
  - vs2022 # [win]
  - gxx    # [unix]
cxx_compiler_version:
  - 8     # [unix]
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 8     # [unix]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  boost:
    max_pin: x.x.x
  mfront:
    max_pin: x.x.x
