{% set name = "mgis" %}
{% set version = "2.2" %}
{% set mfront_ver = "4.1.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz
#    sha256: f5b556aab130da0c423f395fe4c35d6bf509dd8fc958242f2e37ea788464aea9

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}" # [not win]
    - cmake >=3.26.4
    - ninja                       # [win]
    #- clang                       # [win]
    #- lld                         # [win]
    - make                        # [not win]
    - autoconf # [not win]

  host:
    - python
    - numpy
    - boost
    - mfront {{ mfront_ver }} =aster_* # [not win]
    - mfront # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - mfront {{ mfront_ver }} =aster_* # [not win]
    - mfront # [win]

#
#test:
#  commands:
#    # Check for libMFrontGenericInterface.so library
#    - test -f $PREFIX/lib/libMFrontGenericInterface.so
#    # Check for mgis and mgis-version executables
#    - mgis --version  # or whatever command to verify its presence
#


about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande