{% set name = "mgis" %}
{% set version = "2.1" %}
{% set mfront_ver = "4.1.0" %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cmake >=3.26.4
    - autoconf
    - python

  host:
    - python
    - numpy >1.22
    - boost
    - mfront {{ mfront_ver }}=aster_*

  run:
    - numpy
    - "{{ pin_compatible('boost', max_pin='x.x.x') }}"
    - mfront {{ mfront_ver }}=aster_*
    - python

about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande