{% set name = "mgis" %}
{% set version = "2.2" %}
{% set build = 2 %}

# prioritize release over debug
{% if build_type == 'release' %}
{% set build = build + 200 %}
{% endif %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz

build:
  number: {{ build}}
  detect_binary_files_with_prefix: true
  string: "py{{ CONDA_PY }}_{{ build_type }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ pin_subpackage(name, 'x.x') }} *{{ build_type}}*

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - cmake >=3.26.4
    - ninja                       # [win]
    - clang                       # [win]
    - make                        # [not win]
    - autoconf # [not win]

  host:
    - python
    - numpy
    - libboost-python-devel
    - mfront *{{ build_type }}*

  run:
    - python
    - {{ pin_compatible('numpy') }}

#
#test:
#  commands:
#    # Check for libMFrontGenericInterface.so library
#    - test -f $PREFIX/lib/libMFrontGenericInterface.so
#    # Check for mgis and mgis-version executables
#    - mgis --version  # or whatever command to verify its presence
#


about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande