context:
  name: mgis
  version: 2.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
#  - git_url: https://github.com/thelfer/MFrontGenericInterfaceSupport.git
#    git_rev: 10cae958a8e97c9f6b61893f80924c119a6f8e67
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cmake >=3.26.4
    - autoconf

  host:
    - python
    - numpy >1.22
    - boost
    - krande/label/dev::mfront

  run:
    - numpy
    - "{{ pin_compatible('boost', max_pin='x.x.x') }}"
    - "{{ pin_compatible('mfront', max_pin='x.x.x') }}"
    - python

about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande