context:
  name: mgis
  version: 2.1
  mfront_ver: 4.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
#  - git_url: https://github.com/thelfer/MFrontGenericInterfaceSupport.git
#    git_rev: 10cae958a8e97c9f6b61893f80924c119a6f8e67
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://github.com/thelfer/MFrontGenericInterfaceSupport/archive/refs/tags/MFrontGenericInterfaceSupport-{{ version }}.tar.gz

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - cmake >=3.26.4
    - autoconf
    - python

  host:
    - python
    - numpy
    - boost
    - mfront {{ mfront_ver }}=aster_*

  run:
    - numpy
    - boost
    - mfront
    - python
#
#test:
#  commands:
#    # Check for libMFrontGenericInterface.so library
#    - test -f $PREFIX/lib/libMFrontGenericInterface.so
#    # Check for mgis and mgis-version executables
#    - mgis --version  # or whatever command to verify its presence
#


about:
  home: https://thelfer.github.io/mgis/web/index.html
  license: Apache-2.0
  license_family: Apache
  summary: 'MGIS - MFrontGenericInterfaceSupport '
  description: |
    This project aims at proving tools (functions, classes, bindings, etc…) to handle behaviours written using MFront generic interface
  doc_url: https://github.com/thelfer/MFrontGenericInterfaceSupport

extra:
  recipe-maintainers:
    - Krande