c_compiler:
  - vs2022   # [win]
  - gcc      # [unix]
c_compiler_version:
  - 10       # [unix]
cxx_compiler:
  - vs2022   # [win]
  - gxx      # [unix]
cxx_compiler_version:
  - 10       # [unix]
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 10       # [unix]

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  numpy:
    max_pin: x.x
  boost:
    max_pin: x.x

numpy:
  - '1.25'

boost:
  - 1.78
