context:
  name: mfront
  version: 4.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}_{{ version }}.tar.gz'
  url: https://github.com/thelfer/tfel/archive/refs/tags/TFEL-{{ version }}.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - numpy >=1.23
    - ninja
  host:
    - cmake
    - make
    - boost
    - numpy >=1.23
    - python
  run:
    - python
    - numpy >=1.23

test:
  commands:
    - sel(linux): test -f $PREFIX/bin/tfelconfig

about:
  home: http://tfel.sourceforge.net
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENCE-GNU-GPL
  summary: MFront, a code generation tool dedicated to material knowledge
  description: |
    MFront is a code generator which translates a set of closely related domain specific languages into plain C++ on top of the TFEL library. Those languages cover three kinds of material knowledge:
    material properties (for instance the Young modulus, the thermal conductivity, etc.)
    mechanical behaviours. Numerical performances of generated mechanical behaviours were given a particular attention. Various benchmarks show that MFront implementations are competitive with native implementations available in the Cast3M, Code-Aster, Abaqus Standard and Cyrano3 solvers.
    simple point-wise models, such as material swelling used in fuel performance codes.
  doc_url: http://tfel.sourceforge.net/documentations.html
  dev_url: http://tfel.sourceforge.net/devel.html

