c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
c_compiler_version:
  - 8       # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
cxx_compiler_version:
  - 8
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 8        # [unix]

# blas
libblas:
  - 3.9 *openblas
libcblas:
  - 3.9 *openblas
liblapack:
  - 3.9 *openblas
liblapacke:
  - 3.9 *openblas
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  zlib:
    max_pin: x.x.x
  bison:
    max_pin: x.x.x
  openmpi: x.x          # [mpi != "nompi"]

numpy:
  - '1.23'

mpi:          # [unix]
  - openmpi   # [unix]
  - nompi     # [unix]

