c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
c_compiler_version:
  - 8       # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
cxx_compiler_version:
  - 8
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 8        # [unix]
libgomp:
  - 8

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  zlib:
    max_pin: x.x.x
  bison:
    max_pin: x.x.x
  openmpi: x.x          # [mpi != "nompi"]

numpy:
  - '1.23'

hdf5:
  - 1.10.6=mpi*
  - 1.10.6=nompi*

mpi:
  - openmpi
  - nompi

zip_keys:
  - mpi
  - hdf5

