context:
  name: scotch
  version: 7.0.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: "codeaster-prerequisites-20221225-oss.tar.gz"
    url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
    folder: deps/
#  - hg_url: http://hg.code.sf.net/p/prereq/scotch
#    hg_tag: '{{ version }}'


build:
  detect_binary_files_with_prefix: true
  number: 2
  script_env:
    PKG_DEBUG: "{{ environ.get('PKG_DEBUG', 'False') }}"

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - sysroot_linux-64 2.17
    - make
    - python
    - zlib
    - bison

  host:
    - python

  run:
    - zlib
    - bison
    - python

test:
  commands:
    # Check for libscotch.a library
    - test -f $PREFIX/lib/libscotch.a
    # Check for scotch.h header
    - test -f $PREFIX/include/scotch.h


about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CeCILL-C free/libre
  license_family: CeCILL-C
  summary: 'Scotch : Package for graph and mesh/hypergraph partitioning, graph clustering, and sparse matrix ordering.'
  description: |
    Package for graph and mesh/hypergraph partitioning, graph clustering, and sparse matrix ordering.
  dev_url: https://gitlab.inria.fr/scotch/scotch

extra:
  recipe-maintainers:
    - Krande