---
mpi:
  - mpich
  - openmpi

scalar:
  - real
  - complex

pin_run_as_build:
  hypre:
    max_pin: x.x.x
  metis:
    max_pin: x.x
  parmetis:
    max_pin: x.x
  scalapack:
    max_pin: x.x
  suitesparse:
    max_pin: x.x  # [not osx]
numpy:
  - '1.23'
hdf5:
  - 1.10.6
libgomp:
  - 12
libgcc-ng:
  - 12
libgfortran5:
  - 12
libstdcxx-ng:
  - 12
libgfortran-ng:
  - 12
