{% set name = "petsc" %}
{% set version = "3.17.1" %}
{% set build = 0 %}
# Dependencies
{% set metis_ver = "5.1.0" %}
{% set parmetis_ver = "4.0.3" %}
{% set scalapack_ver = "2.1.0" %}
{% set scotch_ver = "7.0.1" %}
{% set mumps_ver = "5.5.1" %}
{% set hdf5_ver = "1.10.6" %}
{% set cython_ver = "0.29.36" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    - fn: "codeaster-prerequisites-20221225-oss.tar.gz"
      url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
      sha256: c03c9662358867ad4753d56b5f87b1687a63b31baeb7127cf179b913edb7e239
      folder: deps/

build:
  skip: true  # [win]
  number: {{ build }}
  string: aster_py{{ CONDA_PY }}_{{mpi}}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'True') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - sysroot_linux-64 2.17
    - cmake
    - make
    - pkg-config
    - gnuconfig   # [unix]

  host:
    - python
    - hdf5
    - yaml
    - numpy
    - libgomp
    - cython {{ cython_ver }}
    - metis {{ metis_ver }}=aster*
    - parmetis {{ parmetis_ver }}
    - scalapack {{ scalapack_ver }}
    - scotch {{ scotch_ver }}=*openmpi*
    - mumps {{ mumps_ver }}=*openmpi*
    - {{ mpi }}

  run:
    - python
    - hdf5
    - yaml
    - numpy
    - libgomp
    - cython {{ cython_ver }}
    - metis {{ metis_ver }}=aster*
    - parmetis {{ parmetis_ver }}
    - scalapack {{ scalapack_ver }}
    - scotch {{ scotch_ver }}=*openmpi*
    - mumps {{ mumps_ver }}=*openmpi*
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/include/petsc.h
    - test -f $PREFIX/lib/libpetsc.so

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
