{% set version = "3.17.1" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}

package:
  name: petsc
  version: {{ version }}

source:
    - fn: "codeaster-prerequisites-20221225-oss.tar.gz"
      url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
      sha256: c03c9662358867ad4753d56b5f87b1687a63b31baeb7127cf179b913edb7e239
      folder: deps/

build:
  skip: true  # [win]
  number: {{ build }}
  string: aster_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cython 0.29.36
    - make
    - pkg-config
    - python
    - numpy
    - gnuconfig   # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - cython 0.29.36
    - numpy
    - cmake
    - {{ mpi }}
    - yaml
    - metis 5.1.0=aster*
    - parmetis 4.0.3
    - scalapack 2.1.0
    - scotch 7.0.1
    - mumps 5.5.1
    - hdf5
  run:
    - {{ mpi }}
    - yaml
    - {{ pin_compatible('numpy') }}
    - metis 5.1.0=aster*
    - parmetis 4.0.3
    - scalapack 2.1.0
    - scotch 7.0.1
    - mumps 5.5.1
    - hdf5

test:
  commands:
    - test -f $PREFIX/include/petsc.h
    - test -f $PREFIX/lib/libpetsc.so

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
