{% set version = "3.17.1" %}
{% set build = 0 %}

{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc
  version: {{ version }}

source:
    - fn: "codeaster-prerequisites-20221225-oss.tar.gz"
      url: https://www.code-aster.org/FICHIERS/prerequisites/codeaster-prerequisites-20221225-oss.tar.gz
      sha256: c03c9662358867ad4753d56b5f87b1687a63b31baeb7127cf179b913edb7e239
      folder: deps/

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('petsc', max_pin='x.x') }}
  track_features:
    - petsc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - pkg-config
    - python
    - gnuconfig   # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - libblas
    - libcblas
    - liblapack
    - cmake
    - {{ mpi }}
    - yaml
    - metis 5.1.0
    - parmetis 4.0.3
    - ptscotch
    - scalapack
    - scotch
    - mumps-mpi
    - hdf5
  run:
    - {{ mpi }}
    - yaml
    - metis 5.1.0
    - parmetis 4.0.3
    - ptscotch
    - scalapack
    - scotch
    - mumps-mpi
    - hdf5

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - jan-janssen
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - martinRenou
    - matthiasdiener
