name: "Setup Rattler Build"
description: "Setup Intel Fortran compiler"
inputs:
  version:
    description: "Version of toolchain or compiler"
    required: false
outputs:
  fc:
    description: "Path to Fortran compiler"
    value: ${{ steps.outputs.outputs.fc }}
runs:
  using: "composite"
  steps: