package:
  name: mingw64
  version: 13.1.0

source:
  url: https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v11.0.1.tar.bz2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - g++ --version
    - gcc --version

about:
  home: https://mingw-w64.org/
  license: GPL-3.0-or-later
  license_family: GPL
  summary: MinGW-w64 toolchain for Windows
  description: |
    MinGW-w64 is a compiler suite for Windows based on the GNU tool chain.
  doc_url: https://mingw-w64.org/
  dev_url: https://sourceforge.net/projects/mingw-w64/
