{% set name = "ifcopenshell" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/IfcOpenShell/IfcOpenShell

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - python
    - occt==7.5.3
    - cgal
    - cmake
    - swig>=3.0.9
    - libboost
    - icu
  run:
    - libgcc    # [osx]
    - python
    - occt ==7.5.3
    - libboost
    - icu

about:
  home: http://ifcopenshell.org
  license: LGPL
