{% set name = "pythonocc-core" %}
{% set version = "7.7.2" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}


# Higher number -> Always prioritize "all" variant over "novtk" variant
{% set build = build + 100 %}   # [variant == "novtk"]
{% set build = build + 200 %}   # [variant == "all"]


#source:
#  git_url: https://github.com/tpaviot/pythonocc-core.git
#  git_rev: 943bf30dbabcac36d3bf4a04d6bbee93fd1597ec
#  git_depth: 1

source:
  url: https://github.com/tpaviot/pythonocc-core/archive/{{ version }}.tar.gz
  sha256: 0f6473be2800a64222ef86a3de70e3beaa2320a3839ebde1b4f6e845a369c0d9

build:
  number: {{ build }}
  string: py{{ CONDA_PY }}_{{ variant }}_h{{ PKG_HASH }}_{{ build }}
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig ==4.1.1

  host:
    - python
    - occt {{ version }} *{{ variant }}*
    - numpy >=1.22

  run:
    - python
    - six
    - occt {{ version }} *{{ variant }}*
    - numpy >=1.22

  run_constrained:
    - occt {{ version }} *{{ variant }}*

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI
    - OCC.Core.MeshDS
    - OCC.Core.Tesselator
  files:
    - test/

  requires:
    - pyqt >=5
    - mypy
    - svgwrite
    - wxpython >=4
    - pyside2 >=5

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package