{% set version = "7.7.2" %}
{% set build = 0 %}
# Set a higher build number if occt contains 'novtk' in the variant name

{% set build = build + 200 %}  # [occt_variant == "novtk"]
{% set build = build + 100 %}  # [occt_variant == "all"]

package:
  name: pythonocc-core
  version: {{ version }}

source:
  git_url: https://github.com/tpaviot/pythonocc-core.git
  git_rev: 943bf30dbabcac36d3bf4a04d6bbee93fd1597ec
  git_depth: 1

build:
  number: {{ build }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig >=4.1.1

  host:
    - python
    - occt
    - numpy >=1.17

  run:
    - python
    - occt
    - six
    - numpy >=1.17

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package