{% set version = "7.7.2" %}
{% set build = 0 %}

# Prioritize the 'novtk' build variant for reduced file size
{% if "novtk" in occt %}
  {% set build = build + 200 %}
  {% set variant_name = "novtk" %}
{% elif "all" in occt %}
  {% set build = build + 100 %}
  {% set variant_name = "all" %}
{% endif %}

package:
  name: pythonocc-core
  version: {{ version }}

source:
  git_url: https://github.com/tpaviot/pythonocc-core.git
  git_rev: 943bf30dbabcac36d3bf4a04d6bbee93fd1597ec
  git_depth: 1

build:
  number: {{ build }}
  string: py{{ CONDA_PY }}_{{ variant_name }}_h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - ninja
    - cmake
    - swig >=4.1.1

  host:
    - python
    - occt
    - numpy >=1.22

  run:
    - python
    - {{ pin_compatible('occt', max_pin='x.x.x') }}
    - six
    - numpy >=1.22

test:
  imports:
    - OCC
    - OCC.Core.BRepPrimAPI

about:
  home: https://github.com/tpaviot/pythonocc-core
  license: LGPL
  summary: An industrial strength 3D CAD python package