c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
fortran_compiler:
  - gfortran # [unix]
python_impl:
  - cpython

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  boost:
    max_pin: x.x
  openblas:
    max_pin: x.x

mpi:
  - openmpi
  - nompi

numpy:
  - 1.25
  - 1.26

python:
  - 3.11
  - 3.12

zip_keys:
  - numpy
  - python