c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
c_compiler_version:
  - 12    # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
cxx_compiler_version:
  - 12
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 12     # [unix]
python_impl:
  - cpython

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  boost:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  openblas:
    max_pin: x.x

boost:
  - 1.78

numpy:
  - '1.25'

mpi:
  - openmpi
  - nompi

hdf5:
  - 1.10.6=mpi*
  - 1.10.6=nompi*

zip_keys:
  - mpi
  - hdf5
