c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
c_compiler_version:
  - 8     # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
cxx_compiler_version:
  - 8
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 8      # [unix]
python_impl:
  - cpython

# blas
libblas:
  - 3.9 *netlib
libcblas:
  - 3.9 *netlib
liblapack:
  - 3.9 *netlib
liblapacke:
  - 3.9 *netlib
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  boost:
    max_pin: x.x
  mfront:
    max_pin: x.x.x
  libmed:
    max_pin: x.x.x
  scotch:
    max_pin: x.x.x
  medcoupling:
    max_pin: x.x.x
  metis:
    max_pin: x.x.x
  mumps:
    max_pin: x.x.x
  mgis:
    max_pin: x.x.x
  homard:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x

boost:
  - 1.78
numpy:
  - '1.23'
hdf5:
  - 1.10.*=nompi*
