{% set name = 'code-aster' %}
{% set version = '16.4.3' %}
{% set med_ver = '4.1.1=aster_*' %}
{% set metis_ver = '5.1.0=aster4*' %}
{% set mfront_ver = '4.1.0=aster_*' %}
{% set mumps_ver = '5.5.1=aster1*' %}
{% set petsc_ver = '3.17.1_aster' %}
{% set scotch_ver = '7.0.1' %}
{% set medcoupling_ver = '9.10.0' %}
{% set homard_ver = '11.12' %}
{% set mgis_ver = '2.1' %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://gitlab.com/codeaster/src/-/archive/{{ version }}/src-{{ version }}.tar.gz

build:
  detect_binary_files_with_prefix: true
  rpaths:
    - lib/
    - lib/aster/
  number: 5
  script_env:
    - PKG_DEBUG={{ environ.get('PKG_DEBUG', 'False') }}

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - sysroot_linux-64 2.17
    - waf
    - pyyaml
    - {{ mpi }}                 # [mpi != "nompi"]
    - petsc                     # [mpi != "nompi"]
    - parmetis                  # [mpi != "nompi"]

  host:
    - python
    - hdf5
    - pybind11-stubgen 1.2
    - llvm-openmp         # [osx]
    - libgomp             # [unix]
    - astor
    - numpy
    - pyyaml
    - boost
    - libblas
    - liblapack
    - metis {{ metis_ver }}
    - scotch {{ scotch_ver }}
    - mumps {{ mumps_ver }}
    - mfront {{ mfront_ver }}
    - libmed {{ med_ver }}
    - mgis {{ mgis_ver }}
    - medcoupling {{ medcoupling_ver }}
    - homard {{ homard_ver }}
    - {{ mpi }}                 # [mpi != "nompi"]
    - petsc                     # [mpi != "nompi"]
    - parmetis                  # [mpi != "nompi"]

  run:
    - python
    - numpy
    - pyyaml
    - llvm-openmp         # [osx]
    - libgomp             # [unix]
    - libopenblas
    - mfront {{ mfront_ver }}
    - libmed {{ med_ver }}
    - metis {{ metis_ver }}
    - mumps {{ mumps_ver }}
    - mgis {{ mgis_ver }}
    - scotch {{ scotch_ver }}
    - medcoupling {{ medcoupling_ver }}
    - homard {{ homard_ver }}
    - hdf5
    - {{ mpi }}                 # [mpi != "nompi"]
    - petsc                     # [mpi != "nompi"]
    - parmetis                  # [mpi != "nompi"]

test:
  imports:
    - code_aster
  commands:
    - run_aster --help
    - python basic_import.py
    - run_ctest -R 'forma01a|sslp114a|mumps02a|mumps01a|zzzz121a' --resutest=../resutest --only-failed-results -j 1
#    - run_ctest -R 'sslp201a|sdld23a|sdnl133b|sdnl133a' --resutest=../cmathissue --only-failed-results -j 1 # related to py310&py39 failing only

  files:
    - basic_import.py


about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande
