context:
  name: code-aster
  version: 15.8.0
  asrun_ver: 2021.1.0
  med_ver: 4.0.0
  metis_ver: 5.1.0_aster4
  mfront_ver: 3.2.1
  mumps_ver: 5.2.1
  scotch_ver: 6.0.4

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://gitlab.com/codeaster/src/-/archive/{{ version }}/src-{{ version }}.tar.gz
    patches:
      - patches/add_stdexcept.patch
  # Modified version of Metis changing integer sizes for indexes (IDXTYPEWIDTH 64) and including headers for direct linking to Aster
  - hg_url: http://hg.code.sf.net/p/prereq/metis
    hg_tag: '{{ metis_ver }}'
    folder: deps/metis-aster
  - hg_url: http://hg.code.sf.net/p/prereq/frontend
    hg_tag: '{{ asrun_ver }}'
    folder: deps/asrun
  - url: https://github.com/thelfer/tfel/archive/TFEL-{{ mfront_ver }}.tar.gz
    folder: deps/mfront
    # Modified version of Mumps changing integer, complex and real sizes to four bytes (fortran kind=4), waf configuration and metis renumbering
#  - url: http://graal.ens-lyon.fr/MUMPS/MUMPS_{{ mumps_ver }}.tar.gz
#    folder: deps/mumps-aster
#    patches:
#    - patches/mumps-aster-diff.patch
#  - url: https://netcologne.dl.sourceforge.net/project/prereq/homard-11.12_aster2.tar.gz
#    sha256: 80425cee117349df8425f801f9a82aadb85fd41a95af25b4397f0e69dd655304
#    folder: deps/homard
build:
  detect_binary_files_with_prefix: true
  number: 0


requirements:
  build:
    - waf
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('gfortran') }}"
    - "libmed {{ med_ver }}"
    - "mfront {{ mfront_ver }}"
    - scotch
#    - metis ==5.1.0
    - mumps-include
#    - mumps-mpi
    - "mumps-seq {{ mumps_ver }}"
    - petsc
    - hdf5
    - numpy
    - glib
    - boost-cpp
  run:
    - "{{ pin_compatible('libmed', max_pin='x.x') }}"
    - "{{ pin_compatible('mfront', max_pin='x.x') }}"
    - "{{ pin_compatible('mumps-seq', max_pin='x.x') }}"
    - scotch
    - mumps-include
#    - mumps-mpi
    - petsc
    - hdf5
    - numpy
    - glib
    - boost-cpp

about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande