context:
  name: code-aster
  version: 16.4.2
  med_ver: 4.1.1=aster_*
  metis_ver: 5.1.0=aster4*
  mfront_ver: 4.1.0=aster_*
  mumps_ver: 5.5.1=aster1*
  petsc_ver: 3.17.1_aster
  scotch_ver: 7.0.1
  medcoupling_ver: 9.10.0
  homard_ver: 11.12
  mgis_ver: 2.1

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
#  - git_url: https://gitlab.com/codeaster/src.git
#    git_depth: 1 # (Defaults to -1/not shallow)
  - fn: '{{ name }}_{{ version }}.tar.gz'
    url: https://gitlab.com/codeaster/src/-/archive/{{ version }}/src-{{ version }}.tar.gz


build:
  detect_binary_files_with_prefix: true
  number: 5

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - waf
    - pyyaml
    - python
    - numpy
    - hdf5
    - libgomp
    - libgfortran5

  host:
    - python
    - numpy
    - pyyaml
    - boost
    - mfront {{ mfront_ver }}
    - libmed {{ med_ver }}
    - metis {{ metis_ver }}
    - mumps {{ mumps_ver }}
    - mgis {{ mgis_ver }}
    - scotch {{ scotch_ver }}
    - medcoupling {{ medcoupling_ver }}
    - homard {{ homard_ver }}

  run:
    - python
    - numpy
    - pyyaml
    - mfront
    - libmed
    - scotch
    - medcoupling
    - metis
    - mumps
    - mgis
    - homard
    - "{{ pin_compatible('hdf5', max_pin='x.x.x' )}}"

test:
  imports:
    - code_aster
  commands:
    - run_aster --help
    - python basic_import.py
    - run_ctest -R 'forma01a|sslp114a|mumps02a|mumps01a|zzzz121a' --resutest=../resutest --only-failed-results -j 1
  files:
    - basic_import.py


about:
  home: https://www.code-aster.org
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  license_family: GPL
  summary: 'Code_Aster : a finite element solver'
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - Krande
