c_compiler:
  - vs2022  # [win]
  - gcc     # [unix]
c_compiler_version:
  - 9       # [unix]
cxx_compiler:
  - vs2022  # [win]
  - gxx     # [unix]
cxx_compiler_version:
  - 9
fortran_compiler:
  - gfortran # [unix]
fortran_compiler_version:
  - 9        # [unix]
libgomp:
  - 9
libgfortran5:
  - 9
pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
numpy:
  - '1.23'
hdf5:
  - 1.10.6
