c_compiler:
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
  - gcc                        # [unix]
c_compiler_version:
  - 8                          # [unix]
cxx_compiler:
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
  - gxx                        # [unix]
cxx_compiler_version:
  - 8                          # [unix]
fortran_compiler:
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:
  - 8                          # [unix]

m2w64_c_compiler:              # [win]
  - m2w64-toolchain            # [win]
m2w64_cxx_compiler:            # [win]
  - m2w64-toolchain            # [win]
m2w64_fortran_compiler:        # [win]
  - m2w64-toolchain            # [win]

libblas:
  - 3.9 *openblas
libcblas:
  - 3.9 *openblas
liblapack:
  - 3.9 *openblas
liblapacke:
  - 3.9 *openblas
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  zlib:
    max_pin: x.x
  openmpi: x.x               # [mpi != "nompi"]

mpi:          # [unix]
  - openmpi   # [unix]
  - nompi     # [unix]

hdf5:
  - 1.10.6=mpi*
  - 1.10.6=nompi*

zip_keys:
  - mpi
  - hdf5

numpy:
  - '1.23'
