c_compiler:
  - m2w64-toolchain            # [win]
  - gcc                        # [unix]
c_compiler_version:
  - 8                          # [unix]
cxx_compiler:
  - m2w64-toolchain            # [win]
  - gxx                        # [unix]
cxx_compiler_version:
  - 8                          # [unix]
fortran_compiler:
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - m2w64-toolchain            # [win64]

fortran_compiler_version:
  - 8                          # [unix]

blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  zlib:
    max_pin: x.x
  openmpi: x.x               # [mpi != "nompi"]

mpi:
  - openmpi                  # [unix] # for now
  - nompi

hdf5:
  - 1.10.6=mpi*             # [unix] # for now
  - 1.10.9=nompi*

zip_keys:
  - mpi
  - hdf5

numpy:
  - '1.23'
