c_compiler:                    # [not win]
  - gcc                        # [unix]
c_compiler_version:            # [not win]
  - 12                         # [unix]
cxx_compiler:                  # [not win]
  - gxx                        # [unix]
cxx_compiler_version:          # [not win]
  - 12                         # [unix]
fortran_compiler:               # [not win]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]

fortran_compiler_version:      # [not win]
  - 12                         # [unix]

blas_impl:
  - openblas

pin_run_as_build:
  gcc:
    max_pin: x.x
  gxx:
    max_pin: x.x
  gfortran:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  zlib:
    max_pin: x.x
  openmpi: x.x               # [mpi != "nompi"]

mpi:
  - openmpi                  # [unix]
  - nompi

hdf5:
  - 1.10.6=mpi*             # [unix]
  - 1.10.6=nompi*           # [unix]
  - 1.10.10=nompi*          # [win]

zip_keys:
  - mpi
  - hdf5

numpy:
  - '1.25'        # [unix]
