name: ci-asrun

# bump 0
on:
  push:
    paths:
      - src/code_aster/asrun/**
      - .github/workflows/ci-asrun.yml
#    branches:
#    - donotrun

env:
  PKG_NAME: asrun
  PKG_PATH: src/code_aster/asrun

jobs:
  build_test:
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py39, distver: '3.9'},
        ]
        platform: [
#          { name: win, distver: windows-2022, pkg_dir: win-64 },
          { name: linux, distver: ubuntu-latest, pkg_dir: linux-64 },
#          { name: macOS, distver: macos-latest pkg_dir: osx-64}
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: set ENV WORK_DIR
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "PKG_DIR=win-64" >> $GITHUB_ENV
            echo "WORK_DIR=C:\\actions-runner\\_work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "PKG_DIR=osx-64" >> $GITHUB_ENV
            echo "WORK_DIR=/Users/runner/work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "PKG_DIR=linux-64" >> $GITHUB_ENV
            echo "WORK_DIR=/home/runner/work" >> $GITHUB_ENV
          fi
      - name: build local packages
        run: |
          conda config --add channels krande
          conda config --add channels krande/label/dev
          conda config --add channels conda-forge
          
          conda config --show-sources
          conda config --remove channels defaults
          conda config --show-sources
          
          mkdir -p ${{ env.WORK_DIR }}/artifacts
          mkdir -p ${{ env.WORK_DIR }}/build
          boa build . --python ${{ matrix.pyver.distver }} --croot ${{ env.WORK_DIR }}/build --output-folder ${{ env.WORK_DIR }}/artifacts --pkg-format=2
        working-directory: ${{ env.PKG_PATH }}

      - name: upload to anaconda
        run: |
          path="${{ env.WORK_DIR }}/artifacts/noarch/*.conda"
          if [ "${{ env.PKG_DIR }}" == 'win-64' ]; then
            path="'$path'"
          fi
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force --user krande --label dev $path
