name: ci-h5py

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-adapydeps.yml
    branches:
      - donotrun

jobs:
  hdf5:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: hdf5
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;numpy=1.25,mpi=openmpi;numpy=1.25"
      description: "Compilations of hdf5"
      use_quetz: "False"
    secrets: inherit
  h5py:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: hdf5
    with:
      package_name: h5py
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;numpy=1.25;hdf5=1.10.9,mpi=openmpi;numpy=1.25;hdf5=1.10.9"
      description: "Compilations of h5py"
      use_quetz: "False"
    secrets: inherit
  ifcopenshell:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: hdf5
    with:
      package_name: ifcopenshell
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "occt=7.7.2=*novtk*;hdf5=1.10.9,occt=7.7.2=*novtk*;hdf5=1.10.9"
      description: "Compilations of ifcopenshell"
      use_quetz: "False"
    secrets: inherit
  netcdf4:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: netcdf4
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;hdf5=1.10.9,mpi=openmpi;hdf5=1.10.9"
      description: "Compilations of netcdf4"
      use_quetz: "False"
    secrets: inherit