name: ci-h5py

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-adapydeps.yml
    branches:
      - donotrun

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      # This is where the conda user and label should be set
      hdf5: '1.10.9'
      numpy: '1.25'
      conda_label: main
      conda_user: krande
      use_quetz: "True"

    steps:
      - name: dummy step
        id: env
        run: |
          echo "go"

  hdf5:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: env
    with:
      package_name: hdf5
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;numpy=${{ needs.env.outputs.numpy }},mpi=openmpi;numpy=${{ needs.env.outputs.numpy }}"
      description: "Compilations of hdf5"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
  h5py:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: [hdf5, env]
    with:
      package_name: h5py
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;numpy=${{ needs.env.outputs.numpy }};hdf5=${{ needs.env.outputs.hdf5 }},mpi=openmpi;numpy=${{ needs.env.outputs.numpy }};hdf5=${{ needs.env.outputs.hdf5 }}"
      description: "Compilations of h5py"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
  ifcopenshell:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: [hdf5, env]
    with:
      package_name: ifcopenshell
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "occt=7.7.2=*novtk*;hdf5=${{ needs.env.outputs.hdf5 }},occt=7.7.2=*novtk*;hdf5=${{ needs.env.outputs.hdf5 }}"
      description: "Compilations of ifcopenshell"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
  netcdf4:
    uses: ./.github/workflows/conda-build-basic.yml
    needs: [hdf5, env]
    with:
      package_name: netcdf4
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi;hdf5=${{ needs.env.outputs.hdf5 }},mpi=openmpi;hdf5=${{ needs.env.outputs.hdf5 }}"
      description: "Compilations of netcdf4"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit