name: ci-asrun

# bump 0
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-asrun.yml
    branches:
    - donotrun

env:
  PKG_NAME: asrun
  PKG_PATH: src/code_aster/asrun
  BLD_PY: 3.9

jobs:
  build_test:
    name: asrun-noarch
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ env.BLD_PY }}

      - name: set ENV WORK_DIR
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "PKG_DIR=win-64" >> $GITHUB_ENV
            echo "WORK_DIR=C:\\actions-runner\\_work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "PKG_DIR=osx-64" >> $GITHUB_ENV
            echo "WORK_DIR=/Users/runner/work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "PKG_DIR=linux-64" >> $GITHUB_ENV
            echo "WORK_DIR=/home/runner/work" >> $GITHUB_ENV
          fi
      - name: build local packages
        run: |
          conda config --add channels krande
          conda config --add channels krande/label/dev
          conda config --add channels conda-forge
          
          conda config --show-sources
          conda config --remove channels defaults
          conda config --show-sources
          
          mkdir -p ${{ env.WORK_DIR }}/artifacts
          mkdir -p ${{ env.WORK_DIR }}/build
          boa build . --python ${{ env.BLD_PY }} --croot ${{ env.WORK_DIR }}/build --output-folder ${{ env.WORK_DIR }}/artifacts --pkg-format=2
        working-directory: ${{ env.PKG_PATH }}

      - name: upload to anaconda
        run: |
          path="${{ env.WORK_DIR }}/artifacts/noarch/*.conda"
          if [ "${{ env.PKG_DIR }}" == 'win-64' ]; then
            path="'$path'"
          fi
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force --user krande --label dev $path
