name: ci-code-aster

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      # This is where the conda user and label should be set
      package_name: code_aster
      code_aster_version: 16.4.2
      conda_label: debug
      conda_user: krandedev
      pkg_dir: src/code_aster
      debug_build: "True"
      mpi: "True"
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
      variants: "mpi=openmpi,mpi=nompi"

    steps:
      - name: dummy step
        id: env
        run: |
          echo "done"

#  build_code_aster:
#    needs: [ env ]
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: ${{ needs.env.outputs.package_name }}
#      boa: false
#      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
#      conda_label: ${{ needs.env.outputs.conda_label }}
#      conda_user: ${{ needs.env.outputs.conda_user }}
#      debug_build: ${{ needs.env.outputs.debug_build }}
#      python_versions: ${{ needs.env.outputs.python_versions }}
#      platforms: ${{ needs.env.outputs.platforms }}
#      variants: ${{ needs.env.outputs.variants }}
#    secrets: inherit

  test_mpi:
#    needs: [ build_code_aster, env ]
    needs: [ env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version: 16.4.3
      mpi: true
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "mpi"
    secrets: inherit

  test_seq:
#    needs: [ build_code_aster, env ]
    needs: [ env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version: 16.4.3
      mpi: false
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "seq"
    secrets: inherit