name: ci-cadquery

on:
  workflow_dispatch:

jobs:
#  build-ocp:
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: ocp
#      conda_channel: "dev"
#      python_versions: "3.12"
#      platforms: "windows-latest"
#      build_env: "rattler"
#      upload_conda: True
#    secrets: inherit
  build-ipopt:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ipopt
      conda_channel: "dev"
      python_versions: "3.12"
      platforms: "windows-latest"
      build_env: "rattler"
      upload_conda: True
    secrets: inherit
#  build-cadquery:
#    needs: [ build-ocp ]
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: cadquery
#      conda_channel: "dev"
#      python_versions: "3.12"
#      platforms: "windows-latest"
#      build_env: "rattler"
#      upload_conda: True
#    secrets: inherit