name: ci-code-aster-batchv2

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-code-aster-batchv2.yml
#    branches:
#      - donotrun
env:
  WORK_DIR: /home/runner/work
  CONDA_LABEL: gcc8crosslinux
  CONDA_USER: krandedev
  CONDA_TOKEN: ${{ secrets.ANACONDA_DEV_TOKEN }}

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
jobs:
  build_batch_libmed:
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: libmed, boa: false },
        ]
        pyver: [ 3.9, 3.10, 3.11 ]
        platform: [ubuntu-latest ] #, windows-latest, macos-latest]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ${{ matrix.package.name }}
      pyver: ${{ matrix.pyver }}
      platform: ${{ matrix.platform }}
      boa: ${{ matrix.package.boa }}
      conda_label: gcc8crosslinux
      conda_user: krandedev
    secrets:
      CONDA_TOKEN: ${{ secrets.ANACONDA_DEV_TOKEN }}

