name: ci-code-aster
# bump 1
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_test:
    name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: code_aster, path: src/code_aster/code_aster },
        ]
        pyver: [
          { name: py39, distver: '3.9'},
#          { name: py310, distver: '3.10'},
        ]
        platform: [
          { name: win, distver: windows-latest },
          { name: linux, distver: ubuntu-latest },
#          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: build local packages
        run: |
          boa build . --python ${{ matrix.pyver.distver }} --croot $GITHUB_WORKSPACE/artifacts --output-folder $GITHUB_WORKSPACE/artifacts
        working-directory: ${{ matrix.package.path }}

      # in the event of success or failure, upload the artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
          path: $GITHUB_WORKSPACE/artifacts

      - name: Upload artifacts if failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
          path: $GITHUB_WORKSPACE/artifacts