name: ci-code-aster-src-win

# bump 1
on:
  workflow_dispatch:
  push:

env:
  INTEL_VARS_PATH: C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env
  VS_VARS_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build
  CONDA_ROOT: C:\Users\runneradmin\micromamba

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C call {0}
    steps:
      - name: Checkout code-aster/src
        run: |
          git clone -b win-support https://gitlab.com/krande/src.git .

      - uses: awvwgk/setup-fortran@v1 # https://github.com/awvwgk/setup-fortran
        id: setup-fortran
        with:
          compiler: intel
          version: '2024.0'

      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: conda/environment.yml
          cache-environment: true
          init-shell: >-
            cmd.exe
            bash
          condarc: |
            channel_priority: strict
            channels:
              - conda-forge

      - name: print all env vars
        run: |
          where python
          printenv

      - name: print some stuff
        run: |
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
          dir "C:\Program Files (x86)\Intel\oneAPI"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler\latest"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env"

      - name: run manually
        continue-on-error: true
        run: |
          echo "Setting compiler env vars"
          set "CC=clang-cl.exe"
          set "CXX=clang-cl.exe"
          set "FC=ifx.exe"

          where python
          where cl
          where ifx

          SET PARENT_DIR=%~dp0
          SET PARENT_DIR=%PARENT_DIR:\=/%

          set ASTER_PLATFORM_MSVC=1
          set ASTER_PLATFORM_WINDOWS=1

          set MKLROOT=%LIBRARY_PREFIX%
          SET MKLROOT=%MKLROOT:\=/%

          SET LIB_PATH_ROOT=%LIBRARY_PREFIX:\=/%
          SET PREF_ROOT=%PREFIX:\=/%

          set LIBPATH_HDF5=%LIB_PATH_ROOT%/lib
          set INCLUDES_HDF5=%LIB_PATH_ROOT%/include

          set LIBPATH_MED=%LIB_PATH_ROOT%/lib
          set INCLUDES_MED=%LIB_PATH_ROOT%/include

          set LIBPATH_METIS=%LIB_PATH_ROOT%/lib
          set INCLUDES_METIS=%LIB_PATH_ROOT%/include

          set LIBPATH_MUMPS=%LIB_PATH_ROOT%/lib
          set INCLUDES_MUMPS=%LIB_PATH_ROOT%/include

          set LIBPATH_SCOTCH=%LIB_PATH_ROOT%/lib
          set INCLUDES_SCOTCH=%LIB_PATH_ROOT%/include

          set TFELHOME=%LIB_PATH_ROOT%

          set LIBPATH_MGIS=%LIB_PATH_ROOT%/bin
          set INCLUDES_MGIS=%LIB_PATH_ROOT%/include

          REM Compiler flags

          REM /MD link with MSVCRT.lib. /FS allow for multithreaded c compiler calls to vc140.pdb (for cl.exe only)
          set CFLAGS=%CFLAGS% /FS /MD

          set FCFLAGS=%FCFLAGS% -fpp /MD /names:lowercase

          set LDFLAGS=%LDFLAGS% /DEBUG

          set INCLUDES_BIBC=%PREF_ROOT%/include

          set DEFINES=H5_BUILT_AS_DYNAMIC_LIB

          REM Clean the build directory
          waf distclean

          REM Install for standard sequential
          waf configure ^
            --use-config-dir=%PARENT_DIR%/config/ ^
            --med-libs=medC ^
            --prefix=%LIBRARY_PREFIX% ^
            --disable-mpi ^
            --install-tests ^
            --disable-petsc ^
            --disable-metis ^
            --disable-scotch ^
            --disable-mumps ^
            --maths-libs=auto ^
            --without-hg

          REM if USE_LOG is set, then log the output to a file
          if %USE_LOG%==1 (
              REM set a datetime variable down to the minute
              @call conda_datetime.bat
              waf build_debug -v > build_debug_%datetimeString%.log 2>&1
              waf install_debug -v > install_debug_%datetimeString%.log 2>&1
          ) else (
              waf build_debug -v
              waf install_debug -v
          )
#
#      - name: Run compilation
#        continue-on-error: true
#        run: |
#          call conda_build.bat

      - name: print log file
        run: |
          type config.log
          type D:\\a\\condapackaging\\condapackaging\\build\\waf-print-msvc-2.bat
        working-directory: build