name: ci-code-aster
# bump 1
on:
  push:
    paths:
      - src/code_aster/code_aster/**
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_test:
    name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: code_aster, path: src/code_aster/code_aster },
        ]
        pyver: [
          { name: py39, distver: '3.9'},
          { name: py310, distver: '3.10'},
        ]
        platform: [
#          { name: win, distver: windows-latest },
          { name: linux, distver: ubuntu-latest },
#          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: Install mingw if on windows
        if: matrix.platform.name == 'win'
        run: |
          choco install mingw

      - name: build local packages
        run: |
          conda config --add channels krande
          conda config --add channels conda-forge
          boa build . --python ${{ matrix.pyver.distver }} --croot ${{ github.workspace }}/artifacts --output-folder ${{ github.workspace }}/artifacts
        working-directory: ${{ matrix.package.path }}