name: ci-code-aster

# bump 1
on:
  workflow_dispatch:
    inputs:
      conda_channel:
        description: 'Conda Channel for dependencies'
        required: true
        type: string
        default: "ca-7371325000"
      code_aster_version:
        description: 'Code Aster Version'
        required: true
        type: string
        default: "17.0.1"
      python_versions:
        description: 'Python Versions'
        required: true
        type: string
        default: "3.11,3.12"
      platforms:
        description: 'Platforms'
        required: true
        type: string
        default: "ubuntu-latest"
      description:
        description: 'Release Description'
        required: true
        type: string
        default: ""
      mpi_variants:
        description: 'mpi variants'
        required: true
        type: string
        default: "mpi=openmpi,mpi=nompi"
      debug_build:
        type: choice
        required: true
        description: Debug build or not
        options:
          - "True"
          - "False"
        default: "True"

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      # This is where the conda user and label should be set
      package_name: code_aster
      code_aster_version: ${{ inputs.code_aster_version }}
      conda_channel: ${{ inputs.conda_channel }}
      debug_build: ${{ inputs.debug_build }}
      python_versions: ${{ inputs.python_versions }}
      platforms: ${{ inputs.platforms }}
      variants: ${{ inputs.mpi_variants }}
      use_quetz: "True"
      extra_build_args: " -m __root__/src/common.yaml"

    steps:
      - name: dummy step
        id: env
        run: |
          echo "done"

  build_code_aster:
    needs: [ env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ${{ needs.env.outputs.package_name }}
      conda_channel: ${{ needs.env.outputs.conda_channel }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
    
  test:
    needs: [ build_code_aster, env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_channel: ${{ needs.env.outputs.conda_channel }}
      code_aster_version:  ${{ needs.env.outputs.code_aster_version }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit