name: ci-code-aster-win

# Bump 1
on:
  push:
    paths:
      - .github/workflows/ci-code-aster-win.yml
#    branches:
#    - donotrun

jobs:
  hdf5:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: hdf5
      conda_label: "windows"
      conda_user: krande
      quetz_extra_channel: compilers
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "windows-latest"
      description: "Compilations of HDF5 for Windows"
      use_quetz: "True"
    secrets: inherit
#  libmed:
##    needs: hdf5
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: libmed
#      conda_label: "windows"
#      conda_user: krande
#      quetz_extra_channel: compilers
#      debug_build: 'False'
#      pkg_dir: src/code_aster
#      python_versions: "3.10,3.11"
#      platforms: "windows-latest"
#      description: "Compilations of LibMED for Windows"
#      use_quetz: "True"
#    secrets: inherit

#  medcoupling:
##    needs: libmed
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: medcoupling
#      conda_label: "windows"
#      conda_user: krande
#      quetz_extra_channel: compilers
#      debug_build: 'False'
#      pkg_dir: src/code_aster
#      python_versions: "3.10,3.11"
#      platforms: "windows-latest"
#      description: "Compilations of medcoupling for Windows"
#      use_quetz: "True"
#    secrets: inherit
