name: ci-code-aster-batchv2

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-code-aster-batchv2.yml
#    branches:
#      - donotrun
env:
  WORK_DIR: /home/runner/work
  CONDA_LABEL: gcc8crosslinux
  CONDA_USER: krandedev
  CONDA_TOKEN: ${{ secrets.ANACONDA_DEV_TOKEN }}

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
jobs:
  build_batch_libmed:
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: libmed, boa: false },
        ]
        pyver: [
          { name: py39, distver: '3.9' },
          { name: py310, distver: '3.10' },
          { name: py311, distver: '3.11' },
        ]
        platform: [
          # { name: win, distver: windows-latest, pkg_dir: win-64 },
          { name: linux, distver: ubuntu-latest, pkg_dir: linux-64 },
          # { name: macOS, distver: macos-latest }
        ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ${{ matrix.package.name }}
      pyver: ${{ matrix.pyver }}
      platform: ${{ matrix.platform }}
      boa: ${{ matrix.package.boa }}
      conda_label: gcc8crosslinux
      conda_user: krandedev
    secrets:
      CONDA_TOKEN: ${{ secrets.ANACONDA_DEV_TOKEN }}

