name: ci-code-aster
# bump 1
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_test:
    name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        package: [
#          { name: code_aster/mfront },
          { name: code_aster/code_aster },
#          { name: code_aster/asrun },
        ]
        pyver: [
          { name: py311, distver: '3.9'},
          { name: py311, distver: '3.10'},
        ]
        platform: [
          { name: win, distver: windows-latest },
          { name: linux, distver: ubuntu-latest },
          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: build local packages
        run: |
          boa build . --python ${{ matrix.pyver.distver }}
        working-directory: src/${{ matrix.package.name }}