name: ci-code-aster

# bump 1
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-code-aster.yml
    branches:
    - donotrun

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      # This is where the conda user and label should be set
      package_name: code_aster
      code_aster_version: 17.0.1
      conda_label: ca-7371325000
      conda_user: krandedev
      pkg_dir: src/code_aster
      debug_build: "True"
      python_versions: "3.11,3.12"
      platforms: "ubuntu-latest"
      variants: "mpi=openmpi,mpi=nompi"
      use_quetz: "True"
      extra_build_args: " -m __root__/src/code_aster/common.yaml"

    steps:
      - name: dummy step
        id: env
        run: |
          echo "done"

  build_code_aster:
    needs: [ env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ${{ needs.env.outputs.package_name }}
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
    
  test_mpi:
    needs: [ build_code_aster, env ]
#    needs: [ env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version:  ${{ needs.env.outputs.code_aster_version }}
      mpi: true
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "mpi"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
    
  test_seq:
    needs: [ build_code_aster, env ]
#    needs: [ env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version:  ${{ needs.env.outputs.code_aster_version }}
      mpi: false
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "seq"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
    secrets: inherit
