name: ci-code-aster

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_code_aster:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: code_aster
      boa: false
      conda_label: mambabuild
      conda_user: krandedev
      conda_upstream_label: debug
      debug_build: 'True'
    secrets: inherit
