name: ci-code-aster-batchv2

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-code-aster-batchv2.yml
#    branches:
#      - donotrun


# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      conda_label: gcc8
      conda_user: krandedev
    steps:
        - uses: actions/checkout@v2
        - name: set outputs
          id: env
          run: |
            echo "conda_label=gcc8" >> $GITHUB_ENV
            echo "conda_user=krandedev" >> $GITHUB_ENV

  build_batch_1:
    uses: ./.github/workflows/conda-build-basic.yml
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: scotch, boa: true },
          { name: metis, boa: false },
          { name: homard, boa: true },
        ]
    with:
      package_name: ${{ matrix.package.name }}
      boa: ${{ matrix.package.boa }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_mumps:
    needs: build_batch_1
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_libmed:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: libmed
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_medcoupling:
    needs: build_batch_libmed
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: medcoupling
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_mfront:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mfront
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_mgis:
    needs: build_batch_mfront
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mgis
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
  build_batch_code_aster:
    needs: [ build_batch_mumps, build_batch_mgis, build_batch_medcoupling ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: code-aster
      boa: false
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
    secrets: inherit
