name: ci-code-aster-batch

# bump 1
on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Release Description'
        required: true
        type: string
        default: ""
      build_selection:
        description: 'Which builds'
        required: true
        type: string
        default: "all,!scotch,!metis,!homard,!libmed,!mfront,!mgis,!parmetis"
      conda_label:
        description: 'Conda Channel for dependencies'
        required: false
        type: string
      python_versions:
        description: 'Python Versions'
        required: true
        type: string
        default: "3.10,3.11"
      platforms:
        description: 'Platforms'
        required: true
        type: string
        default: "ubuntu-latest"
      code_aster_version:
        description: 'Code Aster version'
        required: true
        type: string
        default: "17.0.1"
      mpi_variants:
        description: 'mpi variants'
        required: true
        type: string
        default: "mpi=openmpi,mpi=nompi"
      debug_build:
        type: choice
        required: true
        description: Debug build or not
        options:
          - "True"
          - "False"
        default: "True"
      extra_build_args:
        description: 'Extra build arguments'
        required: true
        type: string
        default: " -m __root__/src/code_aster/common.yaml"



# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      conda_user: krandedev
      pkg_dir: src/code_aster
      use_quetz: "True"
      # This is where the conda user and label should be set
      code_aster_version: ${{ inputs.code_aster_version }}
      conda_label: ${{ steps.env.outputs.unique_suffix }}
      debug_build: ${{ inputs.debug_build }}
      python_versions: ${{ inputs.python_versions }}
      platforms: ${{ inputs.platforms }}
      mpi_variants: ${{ inputs.mpi_variants }}
      description: ${{ inputs.description }}
      extra_build_args: ${{ inputs.extra_build_args }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toposort==1.10
          pip install ./src/cpack

      - name: dummy step
        id: env
        shell: python
        env:
          CONDA_LABEL: ${{ inputs.conda_label }}
        run: |
          import os
          
          conda_label = os.getenv('CONDA_LABEL', None)
          if not conda_label:
              conda_label = "ca-${{ github.run_id }}"
          
          print(f"{conda_label=}")
          
          env_file = os.environ.get("GITHUB_OUTPUT", None)
          with open(env_file, "a") as my_file:
              my_file.write(f"unique_suffix={conda_label}\n")

  build_batch_1:
    needs: env
    uses: ./.github/workflows/conda-build-basic.yml
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: scotch, boa: false },
          { name: metis, boa: false },
          { name: homard, boa: false },
        ]
    with:
      package_name: ${{ matrix.package.name }}
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: ${{ matrix.package.name }}
    secrets: inherit

  build_mpi_parmetis:
    needs: [env]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: parmetis
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: parmetis
    secrets: inherit

  build_batch_mumps:
    needs: [ build_batch_1, env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.mpi_variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: mumps
    secrets: inherit

  build_batch_libmed:
    needs: env
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: libmed
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.mpi_variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: libmed
    secrets: inherit

  build_batch_petsc:
    needs: [ build_batch_mumps, build_mpi_parmetis, env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: petsc
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: petsc
    secrets: inherit

  build_batch_medcoupling:
    needs: [ build_batch_libmed, build_batch_petsc, env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: medcoupling
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.mpi_variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: medcoupling
    secrets: inherit

  build_batch_mfront:
    needs: [ env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mfront
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: mfront
    secrets: inherit

  build_batch_mgis:
    needs: [ build_batch_mfront, env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mgis
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: mgis
    secrets: inherit

  build_batch_code_aster:
    needs: [ build_batch_mumps, build_batch_mgis, build_batch_medcoupling, env ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: code_aster
      pkg_dir: ${{ needs.env.outputs.pkg_dir }}
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      debug_build: ${{ needs.env.outputs.debug_build }}
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      variants: ${{ needs.env.outputs.mpi_variants }}
      extra_build_args: ${{ needs.env.outputs.extra_build_args }}
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      build_selection: ${{ inputs.build_selection }}
      job_name: code_aster
      env_vars: "CODE_ASTER_VERSION=${{ needs.env.outputs.code_aster_version }}"
    secrets: inherit

  test_mpi:
    needs: [ build_batch_code_aster, env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version: ${{ needs.env.outputs.code_aster_version }}
      mpi: true
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "mpi"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      description:  ${{ needs.env.outputs.description }}
    secrets: inherit

  test_seq:
    needs: [ build_batch_code_aster, env ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.env.outputs.conda_label }}
      conda_user: ${{ needs.env.outputs.conda_user }}
      code_aster_version: ${{ needs.env.outputs.code_aster_version }}
      mpi: false
      python_versions: ${{ needs.env.outputs.python_versions }}
      platforms: ${{ needs.env.outputs.platforms }}
      suffix: "seq"
      use_quetz: ${{ needs.env.outputs.use_quetz }}
      description:  ${{ needs.env.outputs.description }}
    secrets: inherit
