name: ci-code-aster-src-win

# bump 1
on:
  workflow_dispatch:
  push:

env:
  INTEL_VARS_PATH: C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env
  VS_VARS_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build
  CONDA_ROOT: C:\Users\runneradmin\micromamba

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C call {0}
    steps:
      - name: Checkout code-aster/src
        run: |
          git clone -b win-support https://gitlab.com/krande/src.git .

      - uses: awvwgk/setup-fortran@v1 # https://github.com/awvwgk/setup-fortran
        id: setup-fortran
        with:
          compiler: intel
          version: '2024.0'

      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: conda/environment.yml
          cache-environment: true
          init-shell: >-
            cmd.exe
            bash
          condarc: |
            channel_priority: strict
            channels:
              - conda-forge

      - name: print all env vars
        run: |
          where python
          printenv

      - name: print some stuff
        run: |
          dir "C:\Program Files (x86)\Intel\oneAPI"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler\latest"
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler\latest\env"

      - name: Run compilation
        continue-on-error: true
        run: |
          call conda_build.bat

      - name: print log file
        run: |
          type config.log
        working-directory: build