name: ci-code-aster

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_code_aster:
    runs-on: ubuntu-latest
    outputs:
      # This is where the conda user and label should be set
      code_aster_version: 16.4.3
      conda_label: debug
      conda_user: krandedev
      pkg_dir: src/code_aster
      debug_build: "True"
      mpi: "True"
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
      mpi_variants: "mpi=openmpi,mpi=nompi"

    steps:
      - name: dummy step
        id: env
        run: |
          echo "done"
#  build_code_aster:
#    uses: ./.github/workflows/conda-build-basic.yml
#    with:
#      package_name: code_aster
#      boa: false
#      pkg_dir: src/code_aster
#      conda_label: debug
#      conda_user: krandedev
#      conda_upstream_label: debug
#      debug_build: 'True'
#      python_versions: "3.10,3.11"
#      platforms: "ubuntu-latest"
#    secrets: inherit

  test_mpi:
    needs: [ build_code_aster ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.build_code_aster.outputs.conda_label }}
      conda_user: ${{ needs.build_code_aster.outputs.conda_user }}
      code_aster_version: 16.4.3
      mpi: true
      python_versions: ${{ needs.build_code_aster.outputs.python_versions }}
      platforms: ${{ needs.build_code_aster.outputs.platforms }}
      suffix: "mpi"
    secrets: inherit

  test_seq:
    needs: [ build_code_aster ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.build_code_aster.outputs.conda_label }}
      conda_user: ${{ needs.build_code_aster.outputs.conda_user }}
      code_aster_version: 16.4.3
      mpi: false
      python_versions: ${{ needs.build_code_aster.outputs.python_versions }}
      platforms: ${{ needs.build_code_aster.outputs.platforms }}
      suffix: "seq"
    secrets: inherit