name: ci-code-aster

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-code-aster.yml
#    branches:
#    - donotrun

jobs:
  build_code_aster:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: code_aster
      boa: false
      pkg_dir: src/code_aster
      conda_label: debug
      conda_user: krandedev
      conda_upstream_label: debug
      debug_build: 'True'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
    secrets: inherit

  test_mpi:
    needs: [ build_code_aster ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.build_code_aster.outputs.conda_label }}
      conda_user: ${{ needs.build_code_aster.outputs.conda_user }}
      code_aster_version: 16.4.3=*openmpi*
      mpi: true
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
    secrets: inherit

  test_seq:
    needs: [ build_code_aster ]
    uses: ./.github/workflows/code-aster-ctest.yml
    with:
      conda_label: ${{ needs.build_code_aster.outputs.conda_label }}
      conda_user: ${{ needs.build_code_aster.outputs.conda_user }}
      code_aster_version: 16.4.3=*seq*
      mpi: false
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
    secrets: inherit