name: ci-flang

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-flang.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      job_name: "flang"
      platforms: "windows-latest"
      pkg_dir: src
      conda_label: devtools
      use_quetz: "True"
      extra_build_args: " -m __root__/src/code_aster/common.yaml"
      use_intel_fortran: 'False'
    secrets: inherit