name: ci-flang

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-flang.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      platforms: "windows-latest"
      use_quetz: "True"
      extra_build_args: ""
      use_intel_fortran: 'False'
    secrets: inherit