name: ci-flang

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-flang.yml
#    branches:
#      - donotrun

jobs:
  llvmdev:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: llvmdev
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  lld:
    needs: [ llvmdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: lld
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  mlir:
    needs: [ llvmdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mlir
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  clangdev:
    needs: [llvmdev]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: clangdev
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  compiler_rt:
    needs: [ clangdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: compiler-rt
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  flang:
    needs: [compiler_rt, mlir]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  flang_activation:
    needs: [flang, lld]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang-activation
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit