name: ci-flang

on:
  workflow_dispatch:
    inputs:
      build_selection:
        description: 'Which builds'
        required: true
        type: string
        default: "all,!llvmdev,!mlir"
  push:
    paths:
      - .github/workflows/ci-flang.yml
#    branches:
#      - donotrun

jobs:
  llvmdev:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: llvmdev
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  lld:
    needs: [ llvmdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: lld
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  mlir:
    needs: [ llvmdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mlir
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  clangdev:
    needs: [ llvmdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: clangdev
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  compiler_rt:
    needs: [ clangdev ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: compiler-rt
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  flang:
    needs: [ compiler_rt, mlir ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit

  flang_activation:
    needs: [ flang, lld ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang-activation
      build_selection: ${{ inputs.build_selection }}
      platforms: "windows-latest"
      conda_channel: "flang"
      upload_conda: True
    secrets: inherit