name: ci-flang

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-flang.yml
#    branches:
#      - donotrun

jobs:
  llvmdev:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      platforms: "windows-latest"
      conda_channel: "flang"
    secrets: inherit

  clangdev:
    needs: [llvmdev]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: clangdev
      platforms: "windows-latest"
      conda_channel: "flang"
    secrets: inherit

  flang:
    needs: [clangdev]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: flang
      platforms: "windows-latest"
      conda_channel: "flang"
    secrets: inherit