name: ci-gmsh

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-gmsh.yml
#    branches:
#    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: gmsh
      boa: false
      conda_label: dev
      conda_user: krande
      debug_build: 'False'
    secrets: inherit