name: ci-hdf5

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-hdf5.yml
#    branches:
#    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: hdf5
      conda_label: "hdf5"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi,mpi=openmpi"
      description: "Compilations of hdf5"
      use_quetz: "True"
      prep_script: "chmod +x /home/runner/work/condapackaging/condapackaging/src/hdf5/mpiexec.sh"
    secrets: inherit