name: ci-hdf5

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-hdf5.yml
      - .github/actions/**/*
      - .github/workflows/conda-build-basic.yml
#    branches:
#    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: hdf5
      conda_channel: "hdf5"
      python_versions: "3.12"
      platforms: "ubuntu-latest,windows-latest"
      variants: "mpi=nompi;build_type=debug,mpi=openmpi;build_type=debug"
      description: "Compilations of hdf5"
      use_intel_fortran: "True"
      use_quetz: "True"
    secrets: inherit