name: ci-homard

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-homard.yml
    branches:
    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: homard
      boa: true
      conda_label: debug
      conda_user: krandedev
      debug_build: 'True'
    secrets: inherit