name: ci-ifcopenshell

on:
  workflow_dispatch:
    inputs:
      extra_build_args:
        description: 'Extra build arguments'
        required: true
        type: string
        default: " -m __root__/src/code_aster/common.yaml -c https://repo.prefix.dev/code-aster"
      python_versions:
        description: 'Python Versions'
        required: true
        type: string
        default: "3.11,3.12"
      conda_label:
        description: 'Conda channel name'
        required: false
        type: string
      platforms:
        description: 'Platforms'
        required: true
        type: string
        default: "windows-latest"
      variants:
        description: 'Build variants'
        required: true
        type: string
        default: "build_type=debug,build_type=release"
      description:
        description: 'Release Description'
        required: false
        type: string
        default: "Compilations of ifcopenshell"
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
    branches:
      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      pkg_dir: src
      conda_label: ${{ inputs.conda_label }}
      conda_user: krandedev
      python_versions: ${{ inputs.python_versions }}
      platforms: ${{ inputs.platforms }}
      variants: ${{ inputs.variants }}
      description: ${{ inputs.description }}
      use_quetz: "True"
      extra_build_args: ${{ inputs.extra_build_args }}

    secrets: inherit