name: ci-ifcopenshell

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      boa: false
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "windows-latest,ubuntu-latest,macos-latest"
      variants: "occt=7.7.2=*novtk*,occt=7.7.2=*all*"
    secrets: inherit