name: ci-ifcopenshell

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      boa: false
      pkg_dir: src/ifcopenshell/daily
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
    secrets: inherit