name: ci-ifcopenshell

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      conda_label: "main"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest"
      variants: "occt=7.7.2=*novtk*;mpi=nompi,occt=7.7.2=*novtk*;mpi=openmpi"
      description: "Compilations of ifcopenshell"
      use_quetz: "False"
    secrets: inherit