name: ci-ifcopenshell

on:
  workflow_dispatch:
    inputs:
      extra_build_args:
        description: 'Extra build arguments'
        required: true
        type: string
        default: " -m __root__/src/code_aster/common.yaml"
      python_versions:
        description: 'Python Versions'
        required: true
        type: string
        default: "3.11,3.12"
      platforms:
        description: 'Platforms'
        required: true
        type: string
        default: "ubuntu-latest"
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
    branches:
      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      conda_label: "main"
      conda_user: krande
      debug_build: 'False'
      python_versions: ${{ inputs.python_versions }}
      platforms: ${{ inputs.platforms }}
      variants: "occt=7.7.2=*novtk*;mpi=nompi,occt=7.7.2=*novtk*;mpi=openmpi"
      description: "Compilations of ifcopenshell"
      use_quetz: "False"
      extra_build_args: ${{ inputs.extra_build_args }}
    secrets: inherit