name: ci-ifcopenshell

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-ifcopenshell.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ifcopenshell
      boa: false
      conda_label: "adapydeps"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "occt=7.7.2=*novtk*;hdf5=1.10.6=*nompi*,occt=7.7.2=*novtk*;hdf5=1.10.6=*mpi*openmpi*"
      description: "Compilations of ifcopenshell"
      use_quetz: "True"
    secrets: inherit