name: ci-intelfortranrt

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-intelfortranrt.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: intelfortranrt
      platforms: "windows-latest"
      conda_channel: devtools
      use_quetz: "True"
    secrets: inherit