name: ci-libmed

# Bump 1
on:
  push:
    paths:
      - .github/workflows/ci-libmed.yml
#    branches:
#    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: libmed
      conda_label: "adapydeps"
      conda_user: krande
      debug_build: 'False'
      pkg_dir: src/code_aster
      python_versions: "3.10,3.11"
      platforms: "windows-latest"
      variants: "mpi=nompi"
      description: "Compilations of LibMED for Windows"
      use_quetz: "True"
    secrets: inherit