name: ci-libmed

on:
  push:
    paths:
      - src/code_aster/libmed/**
      - .github/workflows/ci-libmed.yml
    branches:
    - donotrun
env:
  PKG_NAME: libmed
  PKG_PATH: src/code_aster/libmed

jobs:
  build_test:
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver:
          - { name: py39, distver: '3.9'}
          - { name: py310, distver: '3.10'}
          - { name: py311, distver: '3.11'}
        platform:
          - { name: win, distver: windows-2022, pkg_dir: win-64 }

    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: set ENV WORK_DIR
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "WORK_DIR=C:\\actions-runner\\_work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "WORK_DIR=/Users/runner/work" >> $GITHUB_ENV
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "WORK_DIR=/home/runner/work" >> $GITHUB_ENV
          fi

      - name: build local packages
        run: |
          artifacts_dir="${{ env.WORK_DIR }}/artifacts"
          build_dir="${{ env.WORK_DIR }}/build"
          
          mkdir -p "$artifacts_dir"
          mkdir -p "$build_dir"
          boa build . --python ${{ matrix.pyver.distver }} --output-folder "$artifacts_dir" --pkg-format=2
        working-directory: ${{ env.PKG_PATH }}

      - name: upload to anaconda
        run: |
          path="${{ env.WORK_DIR }}/artifacts/${{ matrix.platform.pkg_dir }}/*.conda"
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force --user krande --label dev "$path"
