name: ci-libmed-win

# Bump 1
on:
  push:
    paths:
      - .github/workflows/ci-libmed-win.yml
#    branches:
#    - donotrun

jobs:
  hdf5:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: hdf5
      conda_label: "windows"
      conda_user: krande
      conda_extra_channel: ${{ secrets.QUETZ_URL }}/get/compilers
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "windows-latest"
      description: "Compilations of HDF5 for Windows"
      extra_build_args: " -m ${{ github.workspace }}/src/hdf5/config.win.gcc.yml"
      use_quetz: "True"
    secrets: inherit
  libmed:
    needs: hdf5
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: libmed
      conda_label: "windows"
      conda_user: krande
      conda_extra_channel: ${{ secrets.QUETZ_URL }}/get/compilers
      extra_build_args: " -m ${{ github.workspace }}/src/hdf5/config.win.gcc.yml"
      debug_build: 'False'
      pkg_dir: src/code_aster
      python_versions: "3.10,3.11"
      platforms: "windows-latest"
#      variants: "mpi=nompi"
      description: "Compilations of LibMED for Windows"
      use_quetz: "True"
    secrets: inherit