name: ci-mumps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-mumps.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      platforms: "windows-latest"
      conda_channel: "test"
      use_intel_fortran: True
      use_devtools: True
      build_env: 'rattler'
      recipe_file: "__root__/src/code_aster/mumps/recipe.yaml"
    secrets: inherit