name: ci-mumps

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      boa: false
      pkg_dir: src/code_aster
      conda_label: debug
      conda_user: krandedev
      debug_build: 'True'
    secrets: inherit