name: ci-metis
# bump 1
on:
  push:
    paths:
      - src/code_aster/metis/**
      - .github/workflows/ci-metis.yml
#    branches:
#    - donotrun

env:
  PKG_NAME: metis
  PKG_PATH: src/code_aster/metis

jobs:
  build_test:
    name: ${{ env.PKG_NAME }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py39, distver: '3.9'},
#          { name: py310, distver: '3.10'},
        ]
        platform: [
#          { name: win, distver: windows-2022, pkg_dir: win-64 },
          { name: linux, distver: ubuntu-latest, pkg_dir: linux-64 },
#          { name: macOS, distver: macos-latest pkg_dir: osx-64}
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - uses: ./.github/actions/boa-build
        with:
          path: ${{ env.PKG_PATH }}
          name: ${{ env.PKG_NAME }}
          python: ${{ matrix.pyver.distver }}
