name: ci-medcoupling

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-medcoupling.yml
#    branches:
#    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: medcoupling
      conda_label: "adapydeps"
      conda_user: krande
      pkg_dir: src/code_aster
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "windows-latest"
      description: "Compilations of medcoupling"
      use_quetz: "True"
    secrets: inherit