name: ci-mumps

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      job_name: "mumps"
      platforms: "windows-latest"
      pkg_dir: src/code_aster
      conda_label: code-aster-dev
      use_quetz: "True"
      extra_build_args: " -m __root__/src/code_aster/common.yaml"
      debug_build: 'True'
    secrets: inherit