name: ci-mumps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/ci-mumps.yml
#    branches:
#      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: mumps
      platforms: "windows-latest"
      use_intel_fortran: 'True'
    secrets: inherit