name: ci-medcoupling

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-medcoupling.yml
    branches:
    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: medcoupling
      boa: false
      pkg_dir: src/code_aster
      conda_label: debug
      conda_user: krandedev
      debug_build: 'True'
    secrets: inherit