name: ci-netcdf4

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: netcdf4
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11"
      platforms: "ubuntu-latest,windows-latest,macos-latest"
      variants: "mpi=nompi,mpi=openmpi"
      description: "Compilations of netcdf4"
      use_quetz: "True"
    secrets: inherit