name: ci-ocp-cadquery

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: cadquery
      conda_channel: "dev"
      python_versions: "3.12"
      platforms: "windows-latest"
      build_env: "rattler"
    secrets: inherit