name: ci-occt

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-occt-core.yml
    branches:
      - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: occt
      boa: false
      conda_label: dev
      conda_user: krande
      debug_build: 'True'
    secrets: inherit