name: ci-ocp

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: ocp
      conda_channel: "dev"
      python_versions: "3.12"
      platforms: "windows-latest"
    secrets: inherit