name: ci-pygfx

# bump 1
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci-pygfx.yml
    branches:
      - donotrun

jobs:
  build_test:
    name: calculix-${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py311, distver: '3.11' },
        ]
        platform: [
          { name: win, distver: windows-latest },
          { name: linux, distver: ubuntu-latest },
          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.conda.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}

      - name: build pygfx packages
        run: |
          conda mambabuild pylinalg --python ${{ matrix.pyver.distver }} -c conda-forge --token ${{ secrets.ANACONDA_TOKEN }} --user krande
          conda mambabuild wgpu --python ${{ matrix.pyver.distver }} -c conda-forge --token ${{ secrets.ANACONDA_TOKEN }} --user krande
          conda mambabuild pygfx --python ${{ matrix.pyver.distver }} -c conda-forge -c krande --token ${{ secrets.ANACONDA_TOKEN }} --user krande
        working-directory: src/pygfx
