name: ci-petsc

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-petsc.yml
    branches:
    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: petsc
      boa: false
      pkg_dir: src/code_aster
      conda_label: debug
      conda_user: krandedev
      debug_build: 'True'
    secrets: inherit