name: ci-pythonocc-core

# bump 1
on:
  push:
    paths:
      - .github/workflows/ci-pythonocc-core.yml
    branches:
    - donotrun

jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: pythonocc-core
      boa: false
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
    secrets: inherit