name: ci-pythonocc-core

on:
  workflow_dispatch:


jobs:
  build:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: pythonocc-core
      conda_label: "dev"
      conda_user: krande
      debug_build: 'False'
      python_versions: "3.10,3.11,3.12"
      variants: "variant=novtk,variant=all"
      use_quetz: "False"
    secrets: inherit
