name: ci-pygfx

on:
  workflow_dispatch:

jobs:
  build_wgpu:
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: wgpu
      boa: false
      pkg_dir: src/pygfx
      conda_label: ""
      conda_user: krande
      debug_build: 'False'
    secrets: inherit

  build_pylinalg:
    needs: [build_wgpu]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: pylinalg
      boa: false
      pkg_dir: src/pygfx
      conda_label: ""
      conda_user: krande
      debug_build: 'False'
    secrets: inherit

  build_pygfx:
    needs: [ build_wgpu ]
    uses: ./.github/workflows/conda-build-basic.yml
    with:
      package_name: pygfx
      boa: false
      pkg_dir: src/pygfx
      conda_label: ""
      conda_user: krande
      debug_build: 'False'
    secrets: inherit


