name: Restart failed runs

on:
  workflow_run:
    workflows: [ ci-force-fail ]
    types:
      - completed

env:
  REPO_OWNER: Krande
  MY_WORKFLOW: ci

jobs:
  restart-failed-runs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Run python script
        run: |
          python check_repo_ci_jobs.py
        working-directory: .github/workflows