name: Restart failed runs

env:
  REPO_OWNER: Krande/condapackaging
  MY_WORKFLOW: ci-git2conda

on:
  workflow_run:
    workflows: [ ci-git2conda ]
    types:
      - completed



jobs:
  restart-failed-runs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: ${{github.event.workflow_run.id }}
        run: echo run identifier ${{ github.event.workflow_run.id }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Use python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          python check_repo_ci_jobs.py
        working-directory: .github/workflows
