name: Restart failed runs

on:
  schedule:
    - cron: '0 * * * *'

env:
  REPO_OWNER: Krande
  MY_WORKFLOW: ci

jobs:
  restart-failed-runs:
    runs-on: ubuntu-latest
    steps:
    - name: Check for failed runs
      id: check-failed-runs
      run: |
        echo "Checking for failed runs..."
        # Replace "my-workflow" with the name of your workflow
        failed_runs=$(curl -s https://api.github.com/repos/$(REPO_OWNER)/REPO/actions/runs?status=completed&conclusion=failure&workflow_id=$(MY_WORKFLOW) | jq '. | map(select(.status.code == 143))')
        echo "Found $(echo $failed_runs | jq length) failed runs"
    - name: Restart failed runs
      if: steps.check-failed-runs.outputs.failed_runs != null
      run: |
        echo "Restarting failed runs..."
        for run_id in $(echo $failed_runs | jq -r '.[].id'); do
          echo "Restarting run $run_id..."
          curl -s -X POST https://api.github.com/repos/$(REPO_OWNER)/REPO/actions/runs/$run_id/rerun \
            -H "Accept: application/vnd.github+json"
        done