name: Simple Release Test

on:
  push:
    paths:
      - .github/workflows/ci-test-package-upload.yml

jobs:
  build_test:
    name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: code_aster, path: src/code_aster/code_aster },
        ]
        pyver: [
          { name: py39, distver: '3.9' },
          { name: py310, distver: '3.10' },
          { name: py311, distver: '3.11' },
        ]
        platform: [
          { name: linux, distver: ubuntu-latest, pkg_dir: linux-64 },
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-name: test-env
          condarc: |
            channels:
              - krande/label/dev
              - conda-forge
          create-args: >-
            python=${{ matrix.pyver.distver }}
            code-aster==16.4.2
            mamba

      - name: Create dummy data
        run: |
          mkdir -p ${{ github.workspace }}/ctest
          mamba list
          echo "$(mamba list)" > ${{ github.workspace }}/ctest/dummy.txt

      - name: Upload ctest for packaging
        uses: actions/upload-artifact@v3
        with:
          name: ctest-${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
          path: ${{ github.workspace }}/ctest

  package:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all ctest artifacts
        uses: actions/download-artifact@v3

      - name: Package ctest directories
        run: |
          tar czf ctest-results.tar.gz ctest-*

      - name: Create Release and Upload Tarball
        uses: softprops/action-gh-release@v1
        with:
          tag_name: code-aster-16.4.2-ctest
          name: CTest Results code-aster-16.4.2
          body: Automated release created on ${{ github.sha }}. Contains ctest results.
          draft: false
          prerelease: false
          files: ctest-results.tar.gz