name: ci-test-matrix-builder

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-test-matrix-builder.yml
#    branches:
#      - donotrun

jobs:
  build_matrix:
    uses: ./.github/workflows/matrix-builder.yml
    with:
      python_versions: "3.10,3.9,3.11"
      platforms: "windows-latest,ubuntu-latest,macOS"

  consume_matrix:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_matrix.outputs.final_matrix) }}
    steps:
      - name: build local packages
        run: |
          echo ${{ matrix.python_versions }}
          echo ${{ matrix.platforms }}