name: Simple Release Test

on:
  push:
    paths:
      - .github/workflows/ci-test-package-upload.yml

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [
          { name: code_aster, path: src/code_aster/code_aster },
        ]
        pyver: [
          { name: py39, distver: '3.9' },
          { name: py310, distver: '3.10' },
          { name: py311, distver: '3.11' },
        ]
        platform: [
          { name: linux, distver: ubuntu-latest, pkg_dir: linux-64 },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create dummy data
        run: |
          mkdir -p ${{ github.workspace }}/ctest
          echo "This is some dummy data for testing." > ${{ github.workspace }}/ctest/dummy.txt

      - name: Upload ctest for packaging
        uses: actions/upload-artifact@v2
        with:
          name: ctest-${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.distver }}
          path: ${{ github.workspace }}/ctest
  package:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all ctest artifacts
        uses: actions/download-artifact@v2

      - name: Package ctest directories
        run: |
          tar czf ctest-results.tar.gz ctest-*

      - name: Create Release and Upload Tarball
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: CTest Results ${{ github.sha }}
          body: Automated release created on ${{ github.sha }}. Contains ctest results.
          draft: false
          prerelease: false
          files: ctest-results.tar.gz