name: ci-ifcopenshell

# bump 0
on:
  push:
    paths:
      - .github/workflows/ci-test-matrix-builder.yml
#    branches:
#      - donotrun

jobs:
  build_matrix:
    uses: ./.github/workflows/matrix-builder.yml
    with:
      python_versions: "3.10,3.9,3.11"
      platform_versions: "windows-latest,ubuntu-latest,macOS"

  consume_matrix:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(needs.build_matrix.outputs.python_matrix) }}
        platform_version: ${{ fromJson(needs.build_matrix.outputs.platform_matrix) }}
    steps:
        - name: build local packages
          run: |
            echo ${{ matrix.python_version }}
            echo ${{ matrix.platform_version }}
          working-directory: src/ifcopenshell/conda