name: ci-git2conda
# bump
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/ci.yml'
    branches:
    - main

jobs:
  build_test:
    name: ${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    strategy:
      fail-fast: false
      matrix:
        package: [{ name: gmsh }]
        pyver: [ { name: py39, distver: '3.9'} ]
        platform: [
          { name: Windows, distver: windows-latest },
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          activate-environment: anaconda-client-env
          python-version: ${{ matrix.pyver.distver }}
          environment-file: environment.yml
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: build conda package
        shell: bash -l {0}
        run: |
          conda-build -c conda-forge src/${{ matrix.package.name }} --python=${{ matrix.pyver.distver }}
