name: ci-git2conda
# bump 3
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml
    branches:
    - main

jobs:
  activate:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    steps:
      - run: echo ok go
  build_test:
    needs: activate
    name: ${{ matrix.package.name }}-${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        package: [
#          { name: ifcopenshell },
#          { name: pythonocc-core },
          { name: gmsh }
        ]
        pyver: [
#          { name: py39, distver: '3.9' },
          { name: py310, distver: '3.10'},
          { name: py311, distver: '3.11'},
        ]
        platform: [
          { name: win, distver: windows-latest },
#          { name: linux, distver: ubuntu-latest },
#          { name: macOS, distver: macos-latest }
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: conda-incubator/setup-miniconda@v2  # https://github.com/conda-incubator/setup-miniconda
        with:
          channel-priority: strict
          channels: conda-forge
          activate-environment: conda-build
          environment-file: environment.conda.yml
          auto-update-conda: false
          python-version: ${{ matrix.pyver.distver }}
      - name: VS install on windows
        if: ${{ matrix.platform.name == 'win' }}
        run: |
          conda install -c conda-forge vs2022_win-64
      - name: build local packages
        run: |
          conda build . --python ${{ matrix.pyver.distver }} -c krande -c conda-forge --token ${{ secrets.ANACONDA_TOKEN }} --user krande --label dev
        working-directory: src/${{ matrix.package.name }}/conda