name: ci-code-aster-batch

# bump 1
on:
  workflow_call:
    inputs:
      package_name:
        description: 'package name'
        type: string
        required: true
      job_name:
        description: 'Name of job'
        type: string
        required: false
        default: ""
      arg_data:
        description: 'A base64 serialized dictionary with all relevant build args. Local build args will always override these.'
        type: string
        required: false
        default: ""
      pkg_dir:
        description: 'work dir'
        type: string
        required: false
        default: src
      work_dir:
        description: 'work dir'
        type: string
        required: false
        default: /home/runner/work
      conda_label:
        description: 'conda label'
        type: string
        required: true
      conda_upstream_label:
        description: 'conda upstream label'
        type: string
        required: false
        default: None
      conda_upstream_user:
        description: 'conda upstream user'
        type: string
        required: false
        default: None
      python_versions:
        description: 'matrix type'
        type: string
        required: false
        default: "3.11"
      platforms:
        description: 'matrix type'
        type: string
        required: false
        default: "windows-latest,ubuntu-latest,macos-latest"
      variants:
        description: 'Variants compiled in parallel; <variant1_key>=<variant1_value>,<variant2_key>=<variant2_value>'
        type: string
        required: false
      use_quetz:
        description: 'use quetz server'
        type: string
        required: false
        default: False
      extra_build_args:
        description: 'extra build args'
        type: string
        required: false
        default: ""
      description:
        description: 'Package channel description (if using quetz)'
        type: string
        required: false
        default: "CondaPackaging Temp Channel"
      prep_script:
        description: 'script to run before build'
        type: string
        required: false
        default: ""
      use_intel_fortran:
        description: 'Install intel fortran'
        type: string
        required: false
        default: False
      build_selection:
        description: 'A comma separated list of jobs'
        type: string
        required: false
        default: ""
      env_vars:
        description: 'A comma separated list of env vars'
        type: string
        required: false
        default: ""
      use_devtools:
        description: 'Use devtools channel'
        type: string
        required: false
        default: False
env:
  CONDA_DIR: ${{ inputs.pkg_dir }}/${{ inputs.package_name }}
  WORK_DIR: ${{ inputs.work_dir }}
  ARTIFACTS_DIR: ${{ inputs.work_dir }}/artifacts
  CROOT_DIR: ${{ inputs.work_dir }}/build
  CLICOLOR_FORCE: "1"
  VARIANT_STR: ""
  CONDA_CHANNEL: ""
  EXTRA_BUILD_ARGS: ""
  CONDA_BUILD_DIR: ""
  SHELL_NAME: bash

jobs:
  build_prep:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    outputs:
      final_matrix: ${{ steps.job-matrix-builder.outputs.final_matrix }}
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - uses: ./.github/actions/job-eval
        id: should_run
        with:
          build_selection: ${{ github.event.inputs.build_selection }}
          job_name: ${{ github.job }}

      - uses: ./.github/actions/job-matrix-builder
        id: job-matrix-builder
        with:
          python_versions: ${{ inputs.python_versions }}
          platforms: ${{ inputs.platforms }}
          variants: ${{ inputs.variants }}

  build_conda:
    needs: [ build_prep ]
    name: ${{ inputs.package_name }}-${{ matrix.platform.short }}-${{ matrix.pyver }}-${{ matrix.variants.value }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_prep.outputs.final_matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - uses: ./.github/actions/job-prep
        with:
          env_vars: ${{ inputs.env_vars }}
          variants: ${{ inputs.variants }}
          variants_base64_str: ${{ matrix.variants.var_str }}
          extra_build_args: ${{ inputs.extra_build_args }}

      - uses: ./.github/actions/install-intel-fortran
        if: ${{ inputs.use_intel_fortran == 'True' }}
        with:
          version: 2025.0.0

      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          environments: "boa"
          cache: true

      - name: Update condarc
        run: |
          pixi run cpack-config --root-dir=${{ env.CROOT_DIR }} --artifacts-dir=${{ env.ARTIFACTS_DIR }}

      - name: build local packages Windows
        if: ${{ runner.os == 'Windows' }}
        shell: cmd /E:on /C call {0}
        run: |
          conda mambabuild . --python ${{ matrix.pyver }}${{ env.VARIANT_STR }}${{ env.EXTRA_BUILD_ARGS }}
        working-directory: ${{ env.CONDA_DIR }}
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}

      - name: build local packages Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          conda mambabuild . --python ${{ matrix.pyver }}${{ env.VARIANT_STR }}${{ env.EXTRA_BUILD_ARGS }}
        working-directory: ${{ env.CONDA_DIR }}
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}

      - name: Upload packages to Quetz Server
        if: ${{ inputs.use_quetz == 'True' }}
        run: |
          cpack-quetz upload ${{ env.ARTIFACTS_DIR }} ${{ inputs.conda_label }} --force
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}
          QUETZ_API_KEY: ${{ secrets.QUETZ_API_KEY }}