name: ci-code-aster-batch

# bump 1
on:
  workflow_call:
    inputs:
      package_name:
        description: 'package name'
        type: string
        required: true
      job_name:
        description: 'Name of job'
        type: string
        required: false
        default: ""
      arg_data:
        description: 'A base64 serialized dictionary with all relevant build args. Local build args will always override these.'
        type: string
        required: false
        default: ""
      pkg_dir:
        description: 'work dir'
        type: string
        required: false
        default: src
      work_dir:
        description: 'work dir'
        type: string
        required: false
        default: /home/runner/work
      conda_label:
        description: 'conda label'
        type: string
        required: true
      conda_user:
        description: 'conda user'
        type: string
        required: false
      conda_upstream_label:
        description: 'conda upstream label'
        type: string
        required: false
        default: None
      conda_upstream_user:
        description: 'conda upstream user'
        type: string
        required: false
        default: None
      python_versions:
        description: 'matrix type'
        type: string
        required: false
        default: "3.11"
      platforms:
        description: 'matrix type'
        type: string
        required: false
        default: "windows-latest,ubuntu-latest,macos-latest"
      variants:
        description: 'Variants compiled in parallel; <variant1_key>=<variant1_value>,<variant2_key>=<variant2_value>'
        type: string
        required: false
      use_quetz:
        description: 'use quetz server'
        type: string
        required: false
        default: False
      extra_build_args:
        description: 'extra build args'
        type: string
        required: false
        default: ""
      description:
        description: 'Package channel description (if using quetz)'
        type: string
        required: false
        default: "CondaPackaging Temp Channel"
      prep_script:
        description: 'script to run before build'
        type: string
        required: false
        default: ""
      use_intel_fortran:
        description: 'Install intel fortran'
        type: string
        required: false
        default: False
      build_selection:
        description: 'A comma separated list of jobs'
        type: string
        required: false
        default: ""
      env_vars:
        description: 'A comma separated list of env vars'
        type: string
        required: false
        default: ""
      use_devtools:
        description: 'Use devtools channel'
        type: string
        required: false
        default: False
env:
  CONDA_DIR: ${{ inputs.pkg_dir }}/${{ inputs.package_name }}
  WORK_DIR: ${{ inputs.work_dir }}
  ARTIFACTS_DIR: ${{ inputs.work_dir }}/artifacts
  CROOT_DIR: ${{ inputs.work_dir }}/build
  CLICOLOR_FORCE: "1"
  VARIANT_STR: ""
  CONDA_CHANNEL: ""
  EXTRA_BUILD_ARGS: ""
  CONDA_BUILD_DIR: ""
  SHELL_NAME: bash

jobs:
  should_run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}
    outputs:
      final_matrix: ${{ steps.job-matrix-builder.outputs.final_matrix }}
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '1'

      - uses: ./.github/actions/job-eval
        id: should_run
        with:
          build_selection: ${{ github.event.inputs.build_selection }}
          job_name: ${{ github.job }}

      - uses: ./.github/actions/job-matrix-builder
        id: job-matrix-builder
              

  # run a preceding job to get the matrix only if matrix_str is None
  build_prep:
    needs: should_run
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    uses: ./.github/workflows/conda-build-prep.yml
    with:
      python_versions: ${{ inputs.python_versions }}
      platforms: ${{ inputs.platforms }}
      variants: ${{ inputs.variants }}
      conda_label: ${{ inputs.conda_label }}
      conda_user: ${{ inputs.conda_user }}
      conda_upstream_label: ${{ inputs.conda_upstream_label }}
      conda_upstream_user: ${{ inputs.conda_upstream_user }}
      use_quetz: ${{ inputs.use_quetz }}
      description: ${{ inputs.description }}
    secrets: inherit

  build_conda:
    needs: [ build_prep ]
    name: ${{ inputs.package_name }}-${{ matrix.platform.short }}-${{ matrix.pyver }}-${{ matrix.variants.value }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_prep.outputs.final_matrix) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - uses: ./.github/actions/job-prep
        with:
          env_vars: ${{ inputs.env_vars }}
          variants: ${{ inputs.variants }}
          variants_base64_str: ${{ matrix.variants.var_str }}
          extra_build_args: ${{ inputs.extra_build_args }}

      - uses: ./.github/actions/install-intel-fortran
        if: ${{ inputs.use_intel_fortran == 'True' }}
        with:
          version: 2025.0.0

      - name: set quetz channel if using quetz or anaconda
        run: |
          if [[ ${{ inputs.use_quetz }} == 'True' ]]; then
            echo "CONDA_CHANNEL=${{ secrets.QUETZ_URL }}/get/${{ needs.build_prep.outputs.conda_upstream_label }}" >> $GITHUB_ENV
          else
            echo "CONDA_CHANNEL=${{ needs.build_prep.outputs.conda_channel }}" >> $GITHUB_ENV
          fi

      - name: use devtools channel
        if: ${{ inputs.use_devtools == 'True' }}
        run: |
          echo "EXTRA_CHANNEL=https://repo.prefix.dev/code-aster" >> $GITHUB_ENV

      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-name: build-env
          cache-environment: true
          init-shell: ${{ env.SHELL_NAME }}
          condarc: |
            remote_max_retries: 5
            remote_backoff_factor: 5
            conda-build:
              root-dir: ${{ env.CROOT_DIR }}
              output_folder: ${{ env.ARTIFACTS_DIR }}
              pkg_format: 2
              zstd_compression_level: 19
            channel_priority: strict
            channels:
              - ${{ env.EXTRA_CHANNEL }}
              - ${{ env.CONDA_CHANNEL }}
              - conda-forge
          create-args: >-
            python=3.11
            anaconda-client
            boa
            python-dotenv
            typer
            quetz-client
            conda-build

      - name: Install cpack-actions
        run: |
          python -m pip install .
        working-directory: src/cpack

      - name: build local packages Windows
        if: ${{ runner.os == 'Windows' }}
        shell: cmd /E:on /C call {0}
        run: |
          conda mambabuild . --python ${{ matrix.pyver }}${{ env.VARIANT_STR }}${{ env.EXTRA_BUILD_ARGS }}
        working-directory: ${{ env.CONDA_DIR }}
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}

      - name: build local packages Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          conda mambabuild . --python ${{ matrix.pyver }}${{ env.VARIANT_STR }}${{ env.EXTRA_BUILD_ARGS }}
        working-directory: ${{ env.CONDA_DIR }}
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}

      - name: Upload packages to Quetz Server
        if: ${{ inputs.use_quetz == 'True' }}
        run: |
          cpack-quetz upload ${{ env.ARTIFACTS_DIR }} ${{ inputs.conda_label }} --force
        env:
          QUETZ_URL: ${{ secrets.QUETZ_URL }}
          QUETZ_API_KEY: ${{ secrets.QUETZ_API_KEY }}

      - name: upload to anaconda
        if: ${{ inputs.use_quetz == 'False' }}
        run: |
          cpack-anaconda ${{ env.ARTIFACTS_DIR }} ${{ inputs.conda_label }} ${{ inputs.conda_user }}
        env:
          CONDA_API_TOKEN: ${{ secrets.CONDA_API_TOKEN }}