# a callable workflow that returns a json string of a matrix for either platforms or python versions
name: ci-matrix-builder

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'matrix type'
        type: string
        required: false
      platforms:
        description: 'matrix type'
        type: string
        required: false

    outputs:
      final_matrix:
        description: "matrix"
        value: ${{ jobs.build.outputs.final_matrix }}

jobs:
  build:
    name: generate matrix
    outputs:
      final_matrix: ${{ steps.set-matrix.outputs.final_matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: set matrix
        id: set-matrix
        run: |
          python_versions="${{ inputs.python_versions }}"
          platforms="${{ inputs.platforms }}"
          python_versions=(${python_versions//,/ })
          platforms=(${platforms//,/ })
          echo "::set-output name=final_matrix::{\"python_versions\": [\"${python_versions[@]}\"], \"platforms\": [\"${platforms[@]}\"]}"