# a callable workflow that returns a json string of a matrix for either platforms or python versions
name: ci-matrix-builder

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'matrix type'
        type: string
        required: false
      platforms:
        description: 'matrix type'
        type: string
        required: false

    outputs:
      final_matrix:
        description: "matrix"
        value: ${{ jobs.build.outputs.final_matrix }}

jobs:
  build:
    name: generate matrix
    outputs:
      final_matrix: ${{ steps.set-matrix.outputs.final_matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: set matrix
        id: set-matrix
        run: |
          python_versions="${{ inputs.python_versions }}"
          platforms="${{ inputs.platforms }}"
          python3 << EOF
          import os
          env_file = os.environ.get("GITHUB_OUTPUT", None)
          
          python_versions = python_versions.split(',') if python_versions else []
          platforms = platforms.split(',') if platforms else []
          matrix = {
            "python_versions": python_versions,
            "platforms": platforms
          }
          
          with open(env_file, "a") as my_file:
            my_file.write(f"final_matrix={matrix}\n")
          
          EOF