name: rattler-build

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'Python version'
        type: string
        required: false
      platforms:
        description: 'Runner OS'
        type: string
        required: false
      variants:
        description: 'Conda package variant; <variant1_key>=<variant1_value>,<variant2_key>=<variant2_value>'
        type: string
        required: false
      conda_label:
        description: 'Conda label'
        type: string
        required: false
      conda_user:
        description: 'Conda user'
        type: string
        required: false
      conda_upstream_label:
        description: 'Conda upstream label'
        type: string
        required: false
        default: None
      conda_upstream_user:
        description: 'Conda upstream user'
        type: string
        required: false
        default: None
      conda_channel_description:
        description: 'Conda channel description'
        type: string
        required: false

jobs:
  build_prep:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/job-matrix-builder
        with:
          python_versions: ${{ inputs.python_versions }}
          platforms: ${{ inputs.platforms }}
          conda_label: ${{ inputs.conda_label }}
          conda_user: ${{ inputs.conda_user }}
          conda_upstream_label: ${{ inputs.conda_upstream_label }}
          conda_upstream_user: ${{ inputs.conda_upstream_user }}
          use_quetz: ${{ inputs.use_quetz }}
          conda_channel_description: ${{ inputs.conda_channel_description }}
          variants: ${{ inputs.variants }}

  run:
    needs: build_prep
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_prep.outputs.final_matrix) }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare job
      uses: ./.github/actions/job-prep
      with:
        variants: 'mpi=nompi'

    - name: Install Intel Fortran
      uses: ./.github/actions/install-intel-fortran
      with:
        version: 2025.0.0

    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.34.0
        cache: true

    - run: pixi run hdf5
